import json, os

path = os.path.join(os.path.dirname(__file__), '..', 'site', 'data', 'countries_repatriation.json')
with open(path, encoding='utf-8') as f:
    data = json.load(f)

countries = {
    "akrotiri-and-dhekelia": {
        "country_key": "akrotiri-and-dhekelia",
        "country_name": "Akrotiri and Dhekelia",
        "country_adjective": "Akrotiri and Dhekelia",
        "flag": "🇬🇧",
        "region": "Eastern Mediterranean",
        "languages": ["English", "Greek"],
        "currency": "Euro (EUR)",
        "british_representation": "British High Commission Nicosia, Cyprus (sovereign UK territory — no consular representation needed; MOD/military chain of command)",
        "embassy_type": "Sovereign Base Area Administration",
        "embassy_city": "Episkopi Cantonment",
        "local_authority_involved": "Sovereign Base Area Administration (SBAA); SBA Police; Her Majesty's Coroner for the SBAs; Cyprus Republic authorities for civilian deaths off-base",
        "main_airports": ["RAF Akrotiri (AKT) — military airfield; civilian connections via Larnaca (LCA) ~45 min or Paphos (PFO) ~30 min, both in Cyprus Republic"],
        "routing_notes": "Akrotiri and Dhekelia are British Sovereign Base Areas in Cyprus, not part of the Republic of Cyprus. UK military personnel and dependants in the SBAs fall under MOD and SBAA jurisdiction. Civilian deaths on or near the base may involve both SBAA and Cyprus Republic authorities depending on location. Most repatriation uses civilian connections via Larnaca (LCA) to UK: Ryanair/Jet2/TUI direct to multiple UK airports approximately 4.5h. RAF Akrotiri may handle military repatriations via military air.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 3,
        "typical_timeline_days_max": 14,
        "timeline_notes": "Military chain of command handles service personnel repatriation. Civilian deaths follow Cyprus/SBAA procedures. Larnaca provides frequent direct UK connections, making civilian timelines relatively short once documentation is in order.",
        "complexity_rating": "Moderate",
        "complexity_notes": "The SBAs are UK sovereign territory, so standard FCDO consular assistance does not apply in the same way as overseas countries. Military families are supported through the MOD casualty notification chain. Civilians must navigate the SBAA Administration, which operates under a distinct legal framework from both UK domestic law and Cyprus Republic law.",
        "required_documents": ["SBAA death certificate or Cyprus Republic death certificate (depending on location)", "SBA Coroner's release (non-natural deaths) or Cyprus Coroner", "Embalming certificate", "Export permit from SBAA Administration", "Airworthiness documentation", "UK receiving funeral director confirmation"],
        "religion_notes": "Military population includes multiple denominations. The local Greek Cypriot population is predominantly Greek Orthodox. Confirm religious requirements with the family.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility in the SBAs. Nearest crematorium is in Cyprus Republic (Limassol). Transfer to Cyprus Republic or repatriation to UK for cremation.",
        "no_go_zones": "Active military zones within the SBAs are restricted. The UN Buffer Zone (Green Line) separates the Republic of Cyprus from Northern Cyprus and passes near some SBA boundaries.",
        "risk_highlights": ["Distinct legal jurisdiction — neither UK domestic law nor Cyprus Republic law applies in full", "Military families should engage MOD casualty team, not FCDO", "Civilian deaths on base boundary may involve both SBAA and Cyprus Republic", "RAF Akrotiri is a military airfield — civilian repatriation uses Larnaca or Paphos"]
    },
    "isle-of-man": {
        "country_key": "isle-of-man",
        "country_name": "Isle of Man",
        "country_adjective": "Manx",
        "flag": "🇮🇲",
        "region": "British Isles",
        "languages": ["English", "Manx Gaelic"],
        "currency": "Isle of Man Pound (IMP) / Pound Sterling (GBP)",
        "british_representation": "Lieutenant Governor (UK Crown representative); no FCDO involvement — Isle of Man is a Crown dependency",
        "embassy_type": "Crown Dependency — no Embassy",
        "embassy_city": "Douglas",
        "local_authority_involved": "Isle of Man Coroner of Inquests; Isle of Man Constabulary; Isle of Man Register of Births, Deaths and Marriages",
        "main_airports": ["Isle of Man Airport (IOM) — direct scheduled services to London Heathrow (LHR), Manchester (MAN), Liverpool (LPL), Edinburgh (EDI), Belfast (BHD) and Dublin (DUB). Flight time to London approximately 1h 10min."],
        "routing_notes": "The Isle of Man is a Crown dependency of the British Crown, not part of the UK. It has its own parliament (Tynwald), legal system, and death registration procedures distinct from England and Wales. Repatriation to mainland UK uses direct scheduled flights from IOM to multiple UK airports. The process is closer to domestic transfer than international repatriation but requires Manx death registration and Coroner's procedures to be completed first.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 3,
        "typical_timeline_days_max": 10,
        "timeline_notes": "Good air connectivity to mainland UK. Timeline governed by Manx Coroner procedures for non-natural deaths. Straightforward natural deaths can be processed quickly.",
        "complexity_rating": "Low",
        "complexity_notes": "The Isle of Man has its own legal system but shares close administrative ties with the UK. Death registration, Coroner procedures, and repatriation logistics are relatively straightforward. FCDO consular assistance does not apply — the Isle of Man is a Crown dependency, not a foreign country.",
        "required_documents": ["Isle of Man death certificate (Registrar of Births, Deaths and Marriages)", "Isle of Man Coroner's order (non-natural deaths)", "Funeral director documentation", "UK receiving funeral director confirmation"],
        "religion_notes": "Predominantly Christian (Anglican, Methodist, Roman Catholic). No specific religious complexities in most cases.",
        "cremation_available": True,
        "cremation_notes": "Isle of Man Crematorium at Glencrutchery Road, Douglas. Cremation available on island before or instead of repatriation.",
        "no_go_zones": "No restricted zones relevant to repatriation.",
        "risk_highlights": ["Crown dependency — FCDO consular assistance does not apply", "Own legal system — Manx death registration required before mainland transfer", "TT motorcycle race period (late May/early June) increases visitor presence and accident risk"]
    },
    "jersey": {
        "country_key": "jersey",
        "country_name": "Jersey",
        "country_adjective": "Jersey",
        "flag": "🇯🇪",
        "region": "Channel Islands",
        "languages": ["English", "Jèrriais (Norman French)"],
        "currency": "Jersey Pound (JEP) / Pound Sterling (GBP)",
        "british_representation": "Lieutenant Governor (UK Crown representative); no FCDO involvement — Jersey is a Crown dependency",
        "embassy_type": "Crown Dependency — no Embassy",
        "embassy_city": "St Helier",
        "local_authority_involved": "Jersey Coroner; States of Jersey Police; Jersey Registry (deaths registration)",
        "main_airports": ["Jersey Airport (JER) — direct scheduled services to London Heathrow (LHR), Gatwick (LGW), City (LCY), Stansted (STN), Bristol (BRS), Manchester (MAN), Edinburgh (EDI), Birmingham (BHX) and Exeter (EXT). Flight time to London approximately 1h."],
        "routing_notes": "Jersey is a Crown dependency of the British Crown, separate from the UK. It has its own legal system based on Norman customary law, distinct courts, and death registration procedures. Repatriation to mainland UK uses direct scheduled flights from Jersey Airport (JER) to multiple UK airports. The Jersey Coroner must authorise release of the body in non-natural deaths before repatriation proceeds.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 3,
        "typical_timeline_days_max": 10,
        "timeline_notes": "Excellent air connectivity to mainland UK. Jersey Coroner procedures are well-established. Timelines are short for natural deaths; non-natural deaths depend on Coroner enquiry.",
        "complexity_rating": "Low",
        "complexity_notes": "Jersey has well-developed repatriation infrastructure given its established links to the UK mainland. The main consideration is the Jersey legal system, which differs from English and Welsh law. FCDO consular assistance does not apply.",
        "required_documents": ["Jersey death certificate (Jersey Registry)", "Jersey Coroner's order (non-natural deaths)", "Funeral director documentation", "UK receiving funeral director confirmation"],
        "religion_notes": "Predominantly Christian. No specific religious complexities in most cases. Jersey has a notable Portuguese community (Roman Catholic).",
        "cremation_available": True,
        "cremation_notes": "Jersey Crematorium at Mont à l'Abbé, St Helier. Cremation available on island.",
        "no_go_zones": "No restricted zones relevant to repatriation.",
        "risk_highlights": ["Crown dependency — FCDO consular assistance does not apply", "Own legal system (Norman customary law) — Jersey Coroner and Registry must be engaged", "High cost of living — some funeral services may reflect island pricing"]
    },
    "guernsey": {
        "country_key": "guernsey",
        "country_name": "Guernsey",
        "country_adjective": "Guernsey",
        "flag": "🇬🇬",
        "region": "Channel Islands",
        "languages": ["English", "Guernésiais (Norman French)"],
        "currency": "Guernsey Pound (GGP) / Pound Sterling (GBP)",
        "british_representation": "Lieutenant Governor (UK Crown representative); no FCDO involvement — Guernsey is a Crown dependency",
        "embassy_type": "Crown Dependency — no Embassy",
        "embassy_city": "St Peter Port",
        "local_authority_involved": "HM Coroner of Guernsey; Guernsey Police; Greffe (civil registration office)",
        "main_airports": ["Guernsey Airport (GCI) — direct scheduled services to London Gatwick (LGW), London City (LCY), Bristol (BRS), Manchester (MAN), Birmingham (BHX), Edinburgh (EDI) and Southampton (SOU). Flight time to London approximately 1h."],
        "routing_notes": "Guernsey is a Crown dependency covering the island of Guernsey, plus the dependencies of Alderney, Sark, Herm and several smaller islets. Deaths on Alderney, Sark or Herm require transfer to Guernsey before air repatriation. Guernsey has its own legal system based on Norman customary law. HM Coroner of Guernsey handles non-natural deaths. Repatriation to mainland UK uses direct scheduled flights from GCI.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 3,
        "typical_timeline_days_max": 14,
        "timeline_notes": "Good air connectivity to UK mainland. Deaths on outer islands (Alderney, Sark, Herm) require sea or air transfer to Guernsey first, which can add 1-3 days.",
        "complexity_rating": "Low",
        "complexity_notes": "Guernsey has well-established repatriation links to the UK mainland. The additional complication is the bailiwick's outer islands — Sark has no airport and Herm is accessible only by boat. Deaths on these islands require transfer to Guernsey. FCDO consular assistance does not apply.",
        "required_documents": ["Guernsey death certificate (Greffe)", "HM Coroner of Guernsey order (non-natural deaths)", "Funeral director documentation", "UK receiving funeral director confirmation"],
        "religion_notes": "Predominantly Christian (Anglican, Roman Catholic, Methodist). No specific religious complexities in most cases.",
        "cremation_available": True,
        "cremation_notes": "Guernsey Crematorium at Foulon Cemetery, St Peter Port. Cremation available on island.",
        "no_go_zones": "No restricted zones relevant to repatriation. Sark prohibits motor vehicles — access is by tractor, horse-drawn transport or boat.",
        "risk_highlights": ["Crown dependency — FCDO consular assistance does not apply", "Outer islands (Sark, Herm, Alderney) require transfer to Guernsey main island before air repatriation", "Sark has no airport and no motor vehicles — logistics for deaths on Sark are more complex"]
    },
    "bonaire": {
        "country_key": "bonaire",
        "country_name": "Bonaire",
        "country_adjective": "Bonairean",
        "flag": "🇧🇶",
        "region": "Caribbean",
        "languages": ["Papiamentu", "Dutch", "English"],
        "currency": "US Dollar (USD)",
        "british_representation": "British Embassy The Hague, Netherlands (non-resident); Honorary Consul Willemstad, Curaçao",
        "embassy_type": "Embassy (non-resident)",
        "embassy_city": "The Hague",
        "local_authority_involved": "Public Entity Bonaire (Openbaar Lichaam Bonaire); Dutch Caribbean Police Force (KPCN); Court of First Instance Bonaire Sint Eustatius Saba (BES Islands); Civil Registry Bonaire",
        "main_airports": ["Flamingo Airport (BON) — direct flights to Amsterdam Schiphol (AMS) ~9h via KLM; connections via Aruba (AUA) ~30 min or Curaçao (CUR) ~20 min for further routing"],
        "routing_notes": "Bonaire is a special municipality of the Netherlands (BES island — Bonaire, Sint Eustatius and Saba), meaning it is legally part of the Netherlands itself, not a separate country. Dutch law applies. Repatriation follows Netherlands legal procedures. KLM operates direct BON–AMS flights. UK consular assistance via British Embassy The Hague; Honorary Consul in Willemstad, Curaçao can provide closer support.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 7,
        "typical_timeline_days_max": 21,
        "timeline_notes": "KLM direct flights BON–AMS operate several times weekly. Amsterdam to UK connections are straightforward. Dutch legal procedures for death registration and Coroner (Officier van Justitie) involvement in non-natural deaths govern the timeline.",
        "complexity_rating": "Moderate",
        "complexity_notes": "Bonaire's status as a special municipality of the Netherlands (not a separate Caribbean country) means Dutch law applies directly. UK families should engage a specialist firm familiar with Dutch Caribbean legal procedures, which differ from Netherlands Antilles procedures that applied pre-2010. Sint Eustatius and Saba are the other BES islands — separate islands with the same framework.",
        "required_documents": ["Dutch death certificate (Civil Registry Bonaire)", "Dutch Coroner's release (Officier van Justitie, non-natural deaths)", "Embalming certificate", "Dutch export permit for human remains", "Airworthiness documentation", "UK receiving funeral director confirmation"],
        "religion_notes": "Predominantly Roman Catholic with Protestant and other Christian denominations. Papiamentu-speaking community has distinct cultural traditions around death and mourning.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility on Bonaire. Remains must be transferred to Curaçao or the Netherlands for cremation.",
        "no_go_zones": "Washington Slagbaai National Park covers the northern third of the island. No restrictions relevant to repatriation logistics.",
        "risk_highlights": ["Dutch Caribbean legal framework — distinct from Netherlands Antilles pre-2010 rules", "No cremation on island — transfer to Curaçao or Netherlands required", "KLM direct service to Amsterdam — most straightforward routing", "Honorary Consul in Willemstad (Curaçao) is closest UK consular support"]
    }
}

for key, country in countries.items():
    data['countries'][key] = country
    print(f"ADDED: {key}")

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Total countries: {len(data['countries'])}")
