import json

with open('site/data/countries_repatriation.json', encoding='utf-8') as f:
    data = json.load(f)

batch = {
    "svalbard": {
        "country_key": "svalbard",
        "country_name": "Svalbard",
        "country_adjective": "Svalbard",
        "flag": "🇸🇯",
        "region": "Arctic",
        "languages": ["Norwegian", "Russian"],
        "currency": "Norwegian krone (NOK)",
        "british_representation": "British Embassy, Oslo, Norway (non-resident)",
        "embassy_type": "Non-resident Embassy",
        "embassy_city": "Oslo",
        "local_authority_involved": "Sysselmannen (Governor of Svalbard); Norwegian law applies; deaths investigated by Norwegian Coroner system",
        "main_airports": ["Longyearbyen Airport, Svalbard (LYR)"],
        "routing_notes": "SAS and Norwegian flights LYR–Oslo (OSL) then Oslo–UK. Also charter scientific/expedition flights. Only Longyearbyen has airport infrastructure; deaths elsewhere on the archipelago require snowmobile, boat, or helicopter transfer to Longyearbyen.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 10,
        "typical_timeline_days_max": 28,
        "timeline_notes": "Arctic location, extreme weather, and very limited infrastructure outside Longyearbyen are the primary timing factors. Deaths in the field (wilderness, glacier, research stations) require significant logistics to reach Longyearbyen.",
        "complexity_rating": "High",
        "complexity_notes": "High Arctic archipelago. Norwegian law but unique Svalbard Treaty status. Field deaths — glacier, wilderness, polar bear attack — are logistically complex. Governor (Sysselmannen) is the sole authority. All documentation in Norwegian requires certified English translation.",
        "required_documents": ["Death certificate (Norwegian civil registration, Svalbard) + certified English translation", "Governor (Sysselmannen) clearance", "SAS or charter cargo documentation", "UK Coroner import notification"],
        "religion_notes": "Predominantly secular/Lutheran. Longyearbyen has a church. Russian Barentsburg settlement is Russian Orthodox.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility in Svalbard. Bodies repatriated to mainland Norway or the UK for cremation.",
        "no_go_zones": "Outside Longyearbyen, a firearm is legally required due to polar bear risk. The Norwegian government requires all visitors outside settlements to carry a rifle. Glaciers and sea ice carry serious crevasse and hypothermia risk.",
        "risk_highlights": "Polar bear attacks outside settlements. Extreme cold, avalanche, and crevasse risk. Very limited medical facilities (Longyearbyen Hospital only). No infrastructure in the vast wilderness areas. Arctic storms can close the airport for days."
    },
    "northern-mariana-islands": {
        "country_key": "northern-mariana-islands",
        "country_name": "Northern Mariana Islands",
        "country_adjective": "Northern Marianan",
        "flag": "🇲🇵",
        "region": "Pacific",
        "languages": ["English", "Chamorro", "Carolinian"],
        "currency": "US dollar (USD)",
        "british_representation": "British Embassy, Tokyo, Japan (non-resident)",
        "embassy_type": "Non-resident Embassy",
        "embassy_city": "Tokyo",
        "local_authority_involved": "CNMI Medical Examiner; CNMI Vital Statistics; US federal and CNMI commonwealth law applies",
        "main_airports": ["Saipan International Airport (SPN)", "Francisco C. Ada/Saipan International Airport"],
        "routing_notes": "No direct UK flights. Routing via Tokyo Narita (NRT) or Guam (GUM) then onward to UK. Limited international service — Japan Airlines and United are main carriers. US federal embalming and documentation requirements apply.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 35,
        "timeline_notes": "Remote western Pacific location, US federal requirements, and limited flight frequency via Tokyo or Guam are the main timing factors. Deaths on outer islands (Tinian, Rota) require inter-island transfer to Saipan.",
        "complexity_rating": "High",
        "complexity_notes": "US commonwealth territory, western Pacific. US federal law governs body export. CNMI Medical Examiner jurisdiction for non-natural deaths. No direct UK routing. British Embassy Tokyo covers non-resident. Deaths on Tinian or Rota require inter-island transfer.",
        "required_documents": ["Death certificate (CNMI Vital Statistics)", "Medical Examiner clearance (non-natural deaths)", "US federal embalming and air transport certificate", "UK Coroner import notification"],
        "religion_notes": "Predominantly Catholic (Chamorro and Carolinian traditional faith). Also non-denominational Protestant communities.",
        "cremation_available": True,
        "cremation_notes": "Cremation available on Saipan.",
        "no_go_zones": "WWII-era unexploded ordnance (UXO) reported in some areas — do not handle or disturb.",
        "risk_highlights": "Typhoon risk June–November. WWII unexploded ordnance in some locations. Limited medical facilities outside Saipan. Deaths on Tinian or Rota require inter-island transfer."
    },
    "wallis-and-futuna": {
        "country_key": "wallis-and-futuna",
        "country_name": "Wallis and Futuna",
        "country_adjective": "Wallisian/Futunan",
        "flag": "🇼🇫",
        "region": "Pacific",
        "languages": ["French", "Wallisian", "Futunan"],
        "currency": "CFP franc (XPF)",
        "british_representation": "British Embassy, Paris, France (non-resident)",
        "embassy_type": "Non-resident Embassy",
        "embassy_city": "Paris",
        "local_authority_involved": "Administrator-Superior (Administrateur superieur); French civil law; Service de l'Etat Civil; Gendarmerie nationale",
        "main_airports": ["Hihifo Airport, Wallis (WLS)", "Futuna Airport (FUT)"],
        "routing_notes": "Air Caledonie International (Aircalin) flights WLS/FUT–Noumea (NOU) New Caledonia, then Air France/Aircalin NOU–Paris CDG. Very limited frequency — Aircalin schedule controls timing. Deaths on Futuna require inter-island flight to Wallis first.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 35,
        "timeline_notes": "Extremely remote French Pacific collectivity. Very limited Aircalin flight frequency. Deaths on Futuna require transfer to Wallis first. Two-leg routing via Noumea to Paris before UK connection.",
        "complexity_rating": "High",
        "complexity_notes": "One of the most remote inhabited French territories. French civil law. All documentation in French requires certified English translation. Two-leg routing via Noumea then Paris CDG. Very limited infrastructure and flight frequency.",
        "required_documents": ["Acte de deces (Service de l'Etat Civil) + certified English translation", "Gendarmerie clearance (non-natural deaths)", "Certificat d'embaumement", "Certificat de non-contagion", "Autorisation de sortie du territoire", "UK Coroner import notification"],
        "religion_notes": "Almost entirely Roman Catholic. Traditional Polynesian customs (Tikanga) may influence family preferences.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility in Wallis and Futuna.",
        "no_go_zones": "None.",
        "risk_highlights": "Extremely limited medical facilities — one hospital on Wallis, basic clinic on Futuna. Cyclone risk. Deaths on Futuna may require emergency medevac to Wallis or New Caledonia for treatment. Very remote."
    },
    "saint-pierre-and-miquelon": {
        "country_key": "saint-pierre-and-miquelon",
        "country_name": "Saint Pierre and Miquelon",
        "country_adjective": "Saint-Pierrais/Miquelonnais",
        "flag": "🇵🇲",
        "region": "North Atlantic / Canada",
        "languages": ["French"],
        "currency": "Euro (EUR)",
        "british_representation": "British Embassy, Paris, France (non-resident)",
        "embassy_type": "Non-resident Embassy",
        "embassy_city": "Paris",
        "local_authority_involved": "Sous-prefet; French civil law; mairie civil registration; Gendarmerie nationale",
        "main_airports": ["Saint-Pierre Airport (FSP)"],
        "routing_notes": "Air Saint-Pierre flights FSP to Halifax (YHZ) Nova Scotia Canada or St John's Newfoundland (YYT), then Air Canada/Air Transat to UK. Very limited frequency. Ferry to Fortune, Newfoundland is an alternative for body transfer in some circumstances.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 10,
        "typical_timeline_days_max": 28,
        "timeline_notes": "French overseas collectivity off the coast of Newfoundland. French civil law and documentation apply. Routing via Canadian airports then UK. Canadian transit requirements may apply.",
        "complexity_rating": "Moderate",
        "complexity_notes": "Small French collectivity 25km off the coast of Newfoundland, Canada. French civil law. All documentation in French requires certified English translation. Unusual routing via Canadian airports — Canadian transit documentation may apply.",
        "required_documents": ["Acte de deces (mairie) + certified English translation", "Gendarmerie clearance (non-natural deaths)", "Certificat d'embaumement", "Certificat de non-contagion", "Autorisation de sortie du territoire", "Canadian transit documentation (if applicable)", "UK Coroner import notification"],
        "religion_notes": "Predominantly Roman Catholic. Small, tight-knit community of approximately 6,000 people.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility in Saint Pierre and Miquelon.",
        "no_go_zones": "None.",
        "risk_highlights": "Dense fog and severe North Atlantic weather frequently disrupt air and ferry services. Very limited medical facilities — serious cases are evacuated to Halifax or St John's."
    },
    "mayotte": {
        "country_key": "mayotte",
        "country_name": "Mayotte",
        "country_adjective": "Mahorais",
        "flag": "🇾🇹",
        "region": "Indian Ocean",
        "languages": ["French", "Shimaore", "Kibushi"],
        "currency": "Euro (EUR)",
        "british_representation": "British Embassy, Paris, France (non-resident)",
        "embassy_type": "Non-resident Embassy",
        "embassy_city": "Paris",
        "local_authority_involved": "Mairie (civil registration); Gendarmerie nationale / Police nationale; French civil law — overseas department of France since 2011",
        "main_airports": ["Dzaoudzi-Pamandzi International Airport (DZD)"],
        "routing_notes": "Mayotte has no long-haul airport — aircraft are limited to narrowbody jets. Routing via Reunion (RUN) or Madagascar (TNR) then Air France to Paris CDG. Some Air Austral services. Two-leg routing adds transit time. No direct flights to mainland France.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 10,
        "typical_timeline_days_max": 28,
        "timeline_notes": "Mayotte has no direct mainland France connection. Two-leg routing via Reunion or Madagascar is required. French civil law documentation applies. Translation of French documents required for UK Coroner.",
        "complexity_rating": "Moderate",
        "complexity_notes": "French overseas department in the Comoros archipelago, Indian Ocean. French civil law. No direct mainland France flight — routing via Reunion or Antananarivo Madagascar adds a transit leg. All documentation in French requires certified English translation.",
        "required_documents": ["Acte de deces (mairie) + certified English translation", "Gendarmerie/Police clearance (non-natural deaths)", "Certificat d'embaumement", "Certificat de non-contagion", "Autorisation de sortie du territoire", "UK Coroner import notification"],
        "religion_notes": "Predominantly Muslim (Sunni, approximately 97%). Islamic burial traditions are strongly observed — timing pressure on repatriation is significant for Muslim families.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility in Mayotte. Cremation is not practised by the predominantly Muslim population.",
        "no_go_zones": "None.",
        "risk_highlights": "Civil unrest and migration crisis have affected Mayotte periodically — check FCDO current advice. Cyclone risk in the Indian Ocean. Limited medical facilities for complex cases. Inter-island boat travel between Grande-Terre and Petite-Terre carries some risk in poor weather."
    }
}

for key, country in batch.items():
    data['countries'][key] = country
    print(f"ADDED: {key}")

with open('site/data/countries_repatriation.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Total countries: {len(data['countries'])}")
