import json

with open('site/data/countries_repatriation.json', encoding='utf-8') as f:
    data = json.load(f)

batch30 = {
    "iraq": {
        "country_key": "iraq",
        "country_name": "Iraq",
        "country_adjective": "Iraqi",
        "flag": "\U0001f1ee\U0001f1f6",
        "region": "Middle East",
        "languages": ["Arabic", "Kurdish"],
        "currency": "Iraqi dinar (IQD)",
        "british_representation": "British Embassy Baghdad (resident). British Consulate Erbil (resident, Kurdistan Region).",
        "embassy_type": "resident",
        "embassy_city": "Baghdad",
        "local_authority_involved": "Civil Status Directorate (Mudiriyyat al-Ahwal al-Madaniyyah), Ministry of Interior, Medico-Legal Directorate",
        "main_airports": ["Baghdad International Airport (BGW)", "Erbil International Airport (EBL)", "Basra International Airport (BSR)"],
        "routing_notes": "Repatriations from Baghdad typically route via Istanbul (Turkish Airlines), Dubai (Emirates/flydubai), or Amman (Royal Jordanian). Erbil has direct Turkish Airlines and other services. Basra uses Dubai as the primary hub.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 56,
        "timeline_notes": "Iraqi civil registration through the Civil Status Directorate. The Medico-Legal Directorate handles forensic aspects where death is not from natural causes. Islamic burial pressure is significant — families should communicate urgency early. Security conditions vary sharply by region; timelines for Baghdad differ considerably from areas of active instability.",
        "complexity_rating": "very-high",
        "complexity_notes": "FCDO advises against all travel to certain provinces and against all but essential travel to most of Iraq. Active security threats include militia groups, residual ISIL activity in disputed territories, and the risk of regional escalation. The Kurdistan Region (Erbil, Sulaymaniyah) is significantly more stable and has better-developed civil administration. Arabic and Kurdish documentation requirements. Islamic burial practices create timeline pressure. Non-Islamic funerals in some areas may face community or administrative resistance.",
        "required_documents": ["Death certificate (shahada wafah)", "Medico-Legal Directorate clearance (if applicable)", "Embalming certificate", "Freedom from infection certificate", "Export permit (Ministry of Interior)", "UK Coroner permission if required", "Consular death registration with British Embassy Baghdad or Consulate Erbil"],
        "religion_notes": "Predominantly Muslim (c.97% — approximately 64% Shia, 32% Sunni). Islamic burial within 24 hours is strongly observed. Repatriation to the UK for Muslim deceased may require specific documentation confirming Islamic rites were observed where possible. Christian and Yazidi minorities exist.",
        "cremation_available": False,
        "cremation_notes": "Cremation is not practised in Iraq and facilities are not available. All remains must be repatriated in full.",
        "no_go_zones": ["Anbar province", "Nineveh Plains (disputed territory)", "Areas near Syrian border", "Southern Baghdad outskirts with militia presence", "Areas of active ISIL activity in northern/western Iraq"],
        "risk_highlights": ["FCDO advises against all travel to some provinces", "Active militia groups and residual ISIL in disputed areas", "Risk of regional escalation involving Iran-backed groups", "Islamic burial timeline pressure — 24-hour expectation", "Significant documentation complexity in Arabic/Kurdish", "Kurdistan Region (Erbil) substantially more manageable than Baghdad or southern Iraq"]
    },
    "afghanistan": {
        "country_key": "afghanistan",
        "country_name": "Afghanistan",
        "country_adjective": "Afghan",
        "flag": "\U0001f1e6\U0001f1eb",
        "region": "South Asia",
        "languages": ["Dari", "Pashto"],
        "currency": "Afghan afghani (AFN)",
        "british_representation": "No resident British Embassy. The UK Embassy in Kabul suspended operations in August 2021. UK nationals requiring consular assistance should contact the FCDO directly or the British Embassy in Islamabad, Pakistan.",
        "embassy_type": "non-resident",
        "embassy_city": "Islamabad",
        "local_authority_involved": "Taliban-controlled civil administration, Ministry of Interior (Taliban government)",
        "main_airports": ["Hamid Karzai International Airport (KBL), Kabul", "Kandahar International Airport (KDH)", "Herat Airport (HEA)"],
        "routing_notes": "Limited commercial air access. Kabul is served by Flydubai, Ariana Afghan Airlines, and Kam Air with connections through Dubai, Istanbul, and Islamabad. Operational status of routes is subject to frequent change. Dubai is the primary hub for UK connections.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 28,
        "typical_timeline_days_max": 120,
        "timeline_notes": "The Taliban government that took power in August 2021 controls civil administration. Documentation processes are conducted through Taliban-controlled ministries. UK recognition issues mean consular registration must be handled via the British Embassy in Islamabad. Timelines are highly variable and unpredictable. Repatriation may not be achievable in all circumstances.",
        "complexity_rating": "very-high",
        "complexity_notes": "FCDO advises against all travel to Afghanistan. The Taliban government has been in control since August 2021; the UK does not formally recognise the Taliban as the legitimate government of Afghanistan. This creates significant complications for consular engagement with Afghan authorities. Active conflict persists in some areas. The country has experienced decades of conflict and infrastructure is severely degraded outside Kabul. Islamic burial within 24 hours is observed — families must communicate urgency immediately. There are very few specialist repatriation firms with active Afghanistan capability.",
        "required_documents": ["Death certificate (issued by Taliban-controlled civil authority)", "Documentation from local authority confirming cause of death", "Embalming certificate (where available)", "Export permit (Taliban Ministry of Interior)", "UK Coroner permission if required", "Consular registration with British Embassy Islamabad"],
        "religion_notes": "Almost entirely Muslim (Sunni majority, Shia minority including Hazara community). Islamic burial within 24 hours is strongly observed. Repatriation processes must be managed with awareness of this requirement.",
        "cremation_available": False,
        "cremation_notes": "Cremation is not practised in Afghanistan. All remains must be repatriated in full.",
        "no_go_zones": ["All areas outside Kabul and major provincial capitals", "Kandahar province", "Helmand province", "Kunar and Nuristan provinces (eastern border)", "Areas near Pakistan and Iranian borders"],
        "risk_highlights": ["FCDO advises against ALL travel to Afghanistan", "No resident UK Embassy — British Embassy Islamabad provides limited assistance", "Taliban control of civil administration creates UK-recognition complications", "Active conflict in multiple provinces", "Very limited specialist firm capability for active Afghanistan cases", "Islamic burial timeline pressure — 24-hour expectation", "Infrastructure severely degraded outside Kabul"]
    },
    "syria": {
        "country_key": "syria",
        "country_name": "Syria",
        "country_adjective": "Syrian",
        "flag": "\U0001f1f8\U0001f1fe",
        "region": "Middle East",
        "languages": ["Arabic"],
        "currency": "Syrian pound (SYP)",
        "british_representation": "No resident British Embassy. The British Embassy in Damascus closed in 2012. UK nationals should contact the FCDO directly. Limited consular assistance may be sought from the British Embassy in Beirut, Lebanon.",
        "embassy_type": "non-resident",
        "embassy_city": "Beirut",
        "local_authority_involved": "Civil Status Directorate. Administration varies by region — post-December 2024 transition government in Damascus; Kurdish SDF in north-east; residual contested areas.",
        "main_airports": ["Damascus International Airport (DAM)", "Aleppo International Airport (ALP) — limited operations", "Latakia Airport (LTK) — limited operations"],
        "routing_notes": "Syria's aviation connectivity is severely limited. Damascus Airport resumed limited commercial operations post-December 2024 following the fall of Assad. Turkish Airlines and Middle Eastern carriers have begun resuming services cautiously. Most repatriation routing is via Beirut (Lebanon) overland then via Middle East hubs, or via Amman (Jordan).",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 28,
        "typical_timeline_days_max": 120,
        "timeline_notes": "Syria is in political transition following the fall of Bashar al-Assad's government in December 2024. Civil administration is in the process of being reconstituted. Documentation processes are highly unpredictable. UK diplomatic presence is absent. Timelines are highly variable and some cases may not be achievable in the near term.",
        "complexity_rating": "very-high",
        "complexity_notes": "FCDO advises against all travel to Syria. The Assad government fell in December 2024 following a rapid advance by HTS (Hayat Tahrir al-Sham) and allied factions. Syria is in political transition. The north-east remains under Kurdish SDF administration. Former regime stronghold areas (Alawite coastal regions) have different local dynamics. Civil registration infrastructure is severely disrupted across much of the country. There is no UK Embassy in Syria. The British Embassy in Beirut provides very limited non-resident assistance subject to current capability. Repatriation is not achievable in many circumstances at present.",
        "required_documents": ["Death certificate (from relevant local authority — varies by region)", "Documentation from local authority on cause of death", "Export permit (from relevant authority)", "UK Coroner permission if required", "Consular registration with British Embassy Beirut (subject to current capability)"],
        "religion_notes": "Predominantly Muslim (c.87% — Sunni majority, Alawite and other Shia minorities). Christian minority (c.10%). Islamic burial within 24 hours is observed in most communities.",
        "cremation_available": False,
        "cremation_notes": "Cremation is not practised in Syria and facilities are not available. All remains must be repatriated in full.",
        "no_go_zones": ["All areas — FCDO advises against all travel", "North-east (SDF-controlled)", "Former conflict zones in Aleppo, Homs, Deir ez-Zor", "Areas near Israeli and Lebanese borders"],
        "risk_highlights": ["FCDO advises against ALL travel to Syria", "Political transition post-December 2024 — Assad government fell, HTS-led transition in Damascus", "No UK Embassy since 2012 — very limited consular assistance available", "Civil registration infrastructure severely disrupted", "Multiple administrative zones with different authorities", "Aviation connectivity severely limited", "Repatriation may not be achievable in many current circumstances"]
    },
    "yemen": {
        "country_key": "yemen",
        "country_name": "Yemen",
        "country_adjective": "Yemeni",
        "flag": "\U0001f1fe\U0001f1ea",
        "region": "Middle East",
        "languages": ["Arabic"],
        "currency": "Yemeni rial (YER)",
        "british_representation": "No resident British Embassy. The British Embassy in Sana'a closed in 2015. UK nationals should contact the FCDO directly. Limited consular assistance is provided by the British Embassy in Riyadh, Saudi Arabia.",
        "embassy_type": "non-resident",
        "embassy_city": "Riyadh",
        "local_authority_involved": "Internationally recognised government (IRG) in Aden/Riyadh — Ministry of Interior; Houthi (Ansar Allah) administration in Sana'a and northern/western Yemen",
        "main_airports": ["Aden International Airport (ADE) — main accessible gateway", "Sana'a International Airport (SAH) — very limited, Houthi-controlled", "Seiyun Airport (GXF) — Hadhramaut, limited access"],
        "routing_notes": "Aden is the main accessible gateway under the internationally recognised government. Flydubai, Air Arabia, and Yemenia operate limited services via Dubai and Amman. Sana'a Airport has very limited and unpredictable scheduled service. Repatriation routing is extremely complex and subject to frequent change.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 28,
        "typical_timeline_days_max": 120,
        "timeline_notes": "Yemen has been in civil conflict since 2014-15. The country is effectively divided between the internationally recognised government (operating from Aden) and the Houthi movement (controlling Sana'a and much of northern/western Yemen). Documentation processes differ by region. Ceasefire arrangements have improved access in some areas. Timelines are highly unpredictable.",
        "complexity_rating": "very-high",
        "complexity_notes": "FCDO advises against all travel to Yemen. Active conflict continues between the Houthis and the internationally recognised government, with Saudi-led coalition involvement. The 2022 UN-brokered truce has been extended but the underlying conflict is unresolved. Civil infrastructure is severely degraded. The humanitarian situation is among the world's worst. Repatriation from Houthi-controlled areas requires working through different authority channels than IRG-controlled areas. British nationals are extremely rare in Yemen; any such case should be treated as a specialist emergency.",
        "required_documents": ["Death certificate (from relevant local authority — IRG or Houthi admin)", "Export permit (from relevant authority)", "Embalming certificate (where available)", "UK Coroner permission if required", "Consular registration with British Embassy Riyadh"],
        "religion_notes": "Almost entirely Muslim (Sunni majority in south/east, Zaydi Shia majority in north). Islamic burial within 24 hours is strongly observed.",
        "cremation_available": False,
        "cremation_notes": "Cremation is not practised in Yemen. All remains must be repatriated in full.",
        "no_go_zones": ["All areas — FCDO advises against all travel", "Active frontline areas (Sa'dah, Ma'rib, Taiz, Hudaydah governorates)", "Red Sea coastal areas (Houthi missile/drone activity)", "Houthi-controlled Sana'a and north-west"],
        "risk_highlights": ["FCDO advises against ALL travel to Yemen", "Active civil conflict — Houthis vs IRG with Saudi-led coalition involvement", "Country divided between two administrations (Houthi/IRG)", "No UK Embassy since 2015 — very limited consular assistance", "Aviation connectivity extremely limited", "Humanitarian crisis — severely degraded infrastructure", "Islamic burial timeline pressure — 24-hour expectation"]
    },
    "turkmenistan": {
        "country_key": "turkmenistan",
        "country_name": "Turkmenistan",
        "country_adjective": "Turkmen",
        "flag": "\U0001f1f9\U0001f1f2",
        "region": "Central Asia",
        "languages": ["Turkmen", "Russian"],
        "currency": "Turkmenistani manat (TMT)",
        "british_representation": "British Embassy Ashgabat (resident).",
        "embassy_type": "resident",
        "embassy_city": "Ashgabat",
        "local_authority_involved": "Civil Registry Office (ZAGS), Ministry of Internal Affairs",
        "main_airports": ["Ashgabat International Airport (ASB)"],
        "routing_notes": "Repatriations route via Istanbul (Turkish Airlines operates Ashgabat to Istanbul) or via Dubai (flydubai). Turkish Airlines is the most reliable carrier for UK-bound connections.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 42,
        "timeline_notes": "Soviet-era civil registration system through ZAGS (Civil Registry Office). Ministry of Internal Affairs issues export permits. The British Embassy in Ashgabat is resident and provides consular support. The authoritarian governance environment means that bureaucratic processing can be unpredictable and may require specialist local contacts.",
        "complexity_rating": "high",
        "complexity_notes": "Turkmenistan is one of the world's most closed and authoritarian states. Foreign nationals have very limited freedom of movement. Internet and communications are heavily restricted, making coordination from the UK difficult. The FCDO advises that consular access to detained British nationals has historically been problematic. Civil registration follows the Soviet ZAGS model. Turkmen-language documentation adds a translation requirement. Access to remote desert regions (Karakum Desert, border areas with Afghanistan) is severely restricted.",
        "required_documents": ["Death certificate (from ZAGS Civil Registry)", "Embalming certificate", "Freedom from infection certificate", "Export permit (Ministry of Internal Affairs)", "UK Coroner permission if required", "Consular death registration with British Embassy Ashgabat"],
        "religion_notes": "Predominantly Muslim (c.93% Sunni). Islamic burial pressure may apply though the state has historically suppressed religious practice. Discuss with specialist firm.",
        "cremation_available": False,
        "cremation_notes": "Cremation is not widely available in Turkmenistan. Repatriation of the body to the UK is the standard approach for UK nationals.",
        "no_go_zones": ["Border regions with Afghanistan", "Remote Karakum Desert interior", "Military restricted zones near Caspian Sea coast"],
        "risk_highlights": ["One of the world's most closed and authoritarian states", "Severe restrictions on foreign national movement and communications", "Bureaucratic unpredictability — specialist local contacts essential", "Border regions with Afghanistan have restricted access", "Resident British Embassy in Ashgabat provides consular support"]
    }
}

for key, country in batch30.items():
    data['countries'][key] = country
    print(f"ADDED: {key}")

with open('site/data/countries_repatriation.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Total countries: {len(data['countries'])}")
