import json

with open('site/data/countries_repatriation.json', encoding='utf-8') as f:
    data = json.load(f)

batch28 = {
    "guinea-bissau": {
        "country_key": "guinea-bissau",
        "country_name": "Guinea-Bissau",
        "country_adjective": "Bissau-Guinean",
        "flag": "\U0001f1ec\U0001f1fc",
        "region": "West Africa",
        "languages": ["Portuguese", "Crioulo"],
        "currency": "West African CFA franc (XOF)",
        "british_representation": "Non-resident. UK consular services provided by the British Embassy in Dakar, Senegal.",
        "embassy_type": "non-resident",
        "embassy_city": "Dakar",
        "local_authority_involved": "Conservatória do Registo Civil (Civil Registry), Polícia Judiciária",
        "main_airports": ["Osvaldo Vieira International Airport (OXB), Bissau"],
        "routing_notes": "Most repatriations route via Dakar (Senegal) or Lisbon (Portugal) using TAP Air Portugal or Air Senegal. Dakar is the primary regional hub.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 42,
        "timeline_notes": "Portuguese civil law documentation through the Conservatória do Registo Civil. Export permit issued by the Ministério da Administração Territorial. Non-resident embassy coverage from Dakar adds coordination time.",
        "complexity_rating": "high",
        "complexity_notes": "Portuguese-language documentation in a country without resident UK diplomatic presence. Institutional capacity is limited outside Bissau. Drug trafficking routes and a history of political coups create an unpredictable environment. FCDO advises heightened vigilance in border areas with Guinea and Senegal's Casamance region.",
        "required_documents": ["Death certificate (certidão de óbito)", "Embalming certificate", "Freedom from infection certificate", "Export permit (Ministério da Administração Territorial)", "UK Coroner permission if required", "Consular death registration with British Embassy Dakar"],
        "religion_notes": "Mix of Islam (c.45%), indigenous beliefs (c.31%), Christianity (c.22%). Islamic burial timeline pressure may apply. Allow for local traditional funerary customs.",
        "cremation_available": False,
        "cremation_notes": "Cremation facilities are not available in Guinea-Bissau. Remains must be repatriated for cremation in the UK.",
        "no_go_zones": ["Northern border regions near Senegal's Casamance area", "Remote eastern border areas with Guinea"],
        "risk_highlights": ["Political instability and history of coups", "Limited infrastructure outside Bissau", "Drug trafficking routes through the country", "Non-resident UK embassy adds coordination delays"]
    },
    "benin": {
        "country_key": "benin",
        "country_name": "Benin",
        "country_adjective": "Beninese",
        "flag": "\U0001f1e7\U0001f1ef",
        "region": "West Africa",
        "languages": ["French"],
        "currency": "West African CFA franc (XOF)",
        "british_representation": "Non-resident. UK consular services provided by the British High Commission in Accra, Ghana.",
        "embassy_type": "non-resident",
        "embassy_city": "Accra",
        "local_authority_involved": "Tribunal de Première Instance, Service de l'État Civil",
        "main_airports": ["Cadjehoun Airport (COO), Cotonou"],
        "routing_notes": "Repatriations typically route via Paris (Air France) or Casablanca (Royal Air Maroc). Ethiopian Airlines serves Cotonou via Addis Ababa.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 35,
        "timeline_notes": "French civil law documentation through Tribunal de Première Instance. Parquet authorisation required before export. Non-resident British High Commission Accra handles consular death registration.",
        "complexity_rating": "moderate",
        "complexity_notes": "Functioning civil registration in Cotonou and major towns. Main complexity is non-resident UK coverage and French-language documentation requirements. Northern border areas near Burkina Faso and Niger have elevated terrorist threat. FCDO advises against all travel within 5km of the Burkina Faso border.",
        "required_documents": ["Acte de décès (death certificate)", "Parquet clearance for export", "Embalming certificate", "Freedom from infection certificate", "Export permit (Ministère de l'Intérieur)", "UK Coroner permission if required", "Consular death registration with British High Commission Accra"],
        "religion_notes": "Mix of Christianity (c.48%), Vodoun and indigenous beliefs (c.28%), Islam (c.24%). Vodoun traditions may involve specific funerary customs that affect timing.",
        "cremation_available": False,
        "cremation_notes": "Cremation facilities are not available in Benin. Remains must be repatriated for cremation in the UK.",
        "no_go_zones": ["Alibori and Atacora departments (northern border with Burkina Faso)", "Border areas with Niger (Malanville area)"],
        "risk_highlights": ["FCDO advises against all travel within 5km of Burkina Faso border", "Jihadist spillover from Sahel into northern departments", "Non-resident UK coverage from Accra adds coordination time"]
    },
    "togo": {
        "country_key": "togo",
        "country_name": "Togo",
        "country_adjective": "Togolese",
        "flag": "\U0001f1f9\U0001f1ec",
        "region": "West Africa",
        "languages": ["French"],
        "currency": "West African CFA franc (XOF)",
        "british_representation": "Non-resident. UK consular services provided by the British High Commission in Accra, Ghana.",
        "embassy_type": "non-resident",
        "embassy_city": "Accra",
        "local_authority_involved": "Tribunal de Première Instance, Service de l'État Civil",
        "main_airports": ["Gnassingbé Eyadéma International Airport (LFW), Lomé"],
        "routing_notes": "Repatriations typically route via Paris (Air France) or Casablanca (Royal Air Maroc). Brussels Airlines and Ethiopian Airlines also serve Lomé.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 35,
        "timeline_notes": "French civil law documentation through Tribunal de Première Instance. Parquet authorisation required before export. Non-resident British High Commission Accra handles consular death registration.",
        "complexity_rating": "moderate",
        "complexity_notes": "Civil registration functions in Lomé and larger towns. Rural documentation gaps can extend timelines. Non-resident UK embassy coverage from Accra. Savanes region in the north has elevated risk due to jihadist spillover from Burkina Faso.",
        "required_documents": ["Acte de décès (death certificate)", "Parquet clearance for export", "Embalming certificate", "Freedom from infection certificate", "Export permit (Ministère de l'Intérieur)", "UK Coroner permission if required", "Consular death registration with British High Commission Accra"],
        "religion_notes": "Mix of Christianity (c.43%), indigenous beliefs (c.35%), Islam (c.14%). Traditional funerary practices vary significantly by ethnic group and region.",
        "cremation_available": False,
        "cremation_notes": "Cremation facilities are not available in Togo. Remains must be repatriated for cremation in the UK.",
        "no_go_zones": ["Savanes region (northern Togo, border with Burkina Faso)"],
        "risk_highlights": ["FCDO advises against all but essential travel to the Savanes region", "Jihadist spillover from Sahel into far north", "Non-resident UK coverage from Accra adds coordination time"]
    },
    "gabon": {
        "country_key": "gabon",
        "country_name": "Gabon",
        "country_adjective": "Gabonese",
        "flag": "\U0001f1ec\U0001f1e6",
        "region": "Central Africa",
        "languages": ["French"],
        "currency": "Central African CFA franc (XAF)",
        "british_representation": "Non-resident. UK consular services provided by the British High Commission in Yaoundé, Cameroon.",
        "embassy_type": "non-resident",
        "embassy_city": "Yaoundé",
        "local_authority_involved": "Tribunal de Première Instance, Service de l'État Civil",
        "main_airports": ["Libreville Leon M'ba International Airport (LBV)"],
        "routing_notes": "Repatriations route via Paris (Air France operates Libreville to Paris CDG) or via Casablanca (Royal Air Maroc). Ethiopian Airlines serves Libreville via Addis Ababa.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 42,
        "timeline_notes": "French civil law documentation through Tribunal de Première Instance. Military transition government since August 2023 may affect administrative processing speeds. Non-resident British High Commission Yaoundé handles consular registration.",
        "complexity_rating": "high",
        "complexity_notes": "The Comité de Transition et de Restauration des Institutions (CTRI) has governed since the August 30 2023 coup ousting President Ali Bongo. Civil administration continues to function but bureaucratic unpredictability remains during transition. Dense forest interior and remote provinces present logistical challenges. Non-resident UK embassy adds coordination time.",
        "required_documents": ["Acte de décès (death certificate)", "Parquet clearance for export", "Embalming certificate", "Freedom from infection certificate", "Export permit (Ministère de l'Intérieur)", "UK Coroner permission if required", "Consular death registration with British High Commission Yaoundé"],
        "religion_notes": "Predominantly Christian (c.75%), with Islam (c.12%) and indigenous beliefs. No significant Islamic burial timeline pressure in most cases.",
        "cremation_available": False,
        "cremation_notes": "Cremation facilities are not available in Gabon. Remains must be repatriated for cremation in the UK.",
        "no_go_zones": ["Remote border areas with Cameroon and Republic of Congo"],
        "risk_highlights": ["Military coup August 2023 — CTRI transitional government in place", "Administrative unpredictability during political transition", "Remote equatorial forest regions with limited infrastructure and no road access", "Non-resident UK coverage from Yaoundé adds coordination time"]
    },
    "republic-of-congo": {
        "country_key": "republic-of-congo",
        "country_name": "Republic of Congo",
        "country_adjective": "Congolese",
        "flag": "\U0001f1e8\U0001f1ec",
        "region": "Central Africa",
        "languages": ["French"],
        "currency": "Central African CFA franc (XAF)",
        "british_representation": "Non-resident. UK consular services provided by the British Embassy in Kinshasa, Democratic Republic of Congo.",
        "embassy_type": "non-resident",
        "embassy_city": "Kinshasa",
        "local_authority_involved": "Tribunal de Grande Instance, Service de l'État Civil",
        "main_airports": ["Maya-Maya Airport (BZV), Brazzaville", "Pointe-Noire Airport (PNR)"],
        "routing_notes": "Repatriations from Brazzaville route via Paris (Air France) or Addis Ababa (Ethiopian Airlines). Pointe-Noire has direct Air France service. Turkish Airlines serves Brazzaville via Istanbul.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 42,
        "timeline_notes": "French civil law documentation through Tribunal de Grande Instance. Civil registration infrastructure is stronger in Brazzaville and Pointe-Noire than in rural areas. Non-resident British Embassy Kinshasa handles consular registration.",
        "complexity_rating": "high",
        "complexity_notes": "Pool department south of Brazzaville has a history of armed militia activity. Rural northern jungle regions (Likouala, Sangha) have very limited infrastructure and logistical access. FCDO advises against all but essential travel to the Pool department. Non-resident UK embassy in Kinshasa across the Congo River adds coordination time.",
        "required_documents": ["Acte de décès (death certificate)", "Parquet clearance for export", "Embalming certificate", "Freedom from infection certificate", "Export permit (Ministère de l'Intérieur)", "UK Coroner permission if required", "Consular death registration with British Embassy Kinshasa"],
        "religion_notes": "Predominantly Christian (c.85%), with a small Muslim minority. No significant Islamic burial timeline pressure in most cases.",
        "cremation_available": False,
        "cremation_notes": "Cremation facilities are not available in the Republic of Congo. Remains must be repatriated for cremation in the UK.",
        "no_go_zones": ["Pool department (history of armed militia activity)", "Remote northern jungle regions (Likouala, Sangha departments)"],
        "risk_highlights": ["FCDO advises against all but essential travel to the Pool department", "Armed militia history in Pool region south of Brazzaville", "Very limited infrastructure in remote northern jungle provinces", "Non-resident UK coverage from Kinshasa adds coordination time"]
    }
}

for key, country in batch28.items():
    data['countries'][key] = country
    print(f"ADDED: {key}")

with open('site/data/countries_repatriation.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Total countries: {len(data['countries'])}")
