import json

with open('site/data/countries_repatriation.json', encoding='utf-8') as f:
    data = json.load(f)

batch = {
    "gibraltar": {
        "country_key": "gibraltar",
        "country_name": "Gibraltar",
        "country_adjective": "Gibraltarian",
        "flag": "🇬🇮",
        "region": "Europe",
        "languages": ["English", "Spanish"],
        "currency": "Gibraltar pound (GIP)",
        "british_representation": "HM Government of Gibraltar (British Overseas Territory — no separate consulate required)",
        "embassy_type": "British Overseas Territory",
        "embassy_city": "Gibraltar",
        "local_authority_involved": "HM Coroner for Gibraltar; Royal Gibraltar Police",
        "main_airports": ["Gibraltar International Airport (GIB)"],
        "routing_notes": "Direct British Airways and easyJet flights GIB–LGW. Short 2.5h flight. Land border with Spain at La Linea de la Concepcion.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 3,
        "typical_timeline_days_max": 10,
        "timeline_notes": "Short flight and English-speaking authorities typically make this one of the faster repatriations. Coroner involvement required for all deaths.",
        "complexity_rating": "Low",
        "complexity_notes": "British Overseas Territory, English common law, English-speaking authorities, direct short-haul flights. Straightforward process.",
        "required_documents": ["Death certificate (issued by Gibraltar Registry)", "HM Coroner Gibraltar clearance", "Funeral director transfer documentation", "UK Coroner import notification"],
        "religion_notes": "Gibraltar has Catholic majority plus Protestant and Jewish communities. Multiple faith funeral facilities available.",
        "cremation_available": True,
        "cremation_notes": "Cremation available in Gibraltar.",
        "no_go_zones": "None.",
        "risk_highlights": "None significant. Standard repatriation process applies."
    },
    "falkland-islands": {
        "country_key": "falkland-islands",
        "country_name": "Falkland Islands",
        "country_adjective": "Falkland Islands",
        "flag": "🇫🇰",
        "region": "South Atlantic",
        "languages": ["English"],
        "currency": "Falkland Islands pound (FKP)",
        "british_representation": "HM Government of the Falkland Islands (British Overseas Territory — no separate consulate required)",
        "embassy_type": "British Overseas Territory",
        "embassy_city": "Stanley",
        "local_authority_involved": "Falkland Islands Coroner; Royal Falkland Islands Police",
        "main_airports": ["Mount Pleasant Airport (MPN)"],
        "routing_notes": "RAF charter flights Brize Norton (BZZ)–Mount Pleasant operated periodically. Commercial LATAM flights via Punta Arenas (PUQ) or Santiago (SCL) Chile. Very limited frequency — RAF routing most practical for repatriation.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 10,
        "typical_timeline_days_max": 30,
        "timeline_notes": "Remote South Atlantic location. RAF flight availability and Coroner process are primary scheduling factors. Delays possible.",
        "complexity_rating": "High",
        "complexity_notes": "Very remote British Overseas Territory with extremely limited flight options. RAF routing coordination adds logistical complexity. Allow significant time.",
        "required_documents": ["Death certificate (Falkland Islands Registry)", "Falkland Islands Coroner clearance", "RAF or airline cargo documentation", "UK Coroner import notification"],
        "religion_notes": "Predominantly Christian (Protestant). Single main church in Stanley.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility in the Falkland Islands.",
        "no_go_zones": "Residual landmine fields from 1982 Falklands War remain in clearly marked areas. Do not enter marked minefields.",
        "risk_highlights": "Residual landmines in marked areas (1982 conflict). Extreme weather and remote terrain. Very limited medical facilities outside Stanley."
    },
    "saint-helena": {
        "country_key": "saint-helena",
        "country_name": "Saint Helena, Ascension and Tristan da Cunha",
        "country_adjective": "Saint Helenian",
        "flag": "🇸🇭",
        "region": "South Atlantic",
        "languages": ["English"],
        "currency": "Saint Helena pound (SHP)",
        "british_representation": "HM Government of Saint Helena (British Overseas Territory — no separate consulate required)",
        "embassy_type": "British Overseas Territory",
        "embassy_city": "Jamestown",
        "local_authority_involved": "Saint Helena Coroner; Saint Helena Police Service",
        "main_airports": ["Saint Helena Airport (HLE)"],
        "routing_notes": "SA Airlink flights HLE–Johannesburg (JNB) approx twice weekly. Onward to UK via JNB. Ascension Island: RAF Wideawake Airfield — military access only. Tristan da Cunha: no airport — ship only (6-day voyage to Cape Town).",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 35,
        "timeline_notes": "Saint Helena Airport opened 2016 but flight frequency is very low. Tristan da Cunha is the most remote inhabited island on earth — ship-only access adds weeks.",
        "complexity_rating": "High",
        "complexity_notes": "Extremely remote. Very limited flight frequency from Saint Helena. Ascension requires military clearance. Tristan da Cunha has no air access whatsoever.",
        "required_documents": ["Death certificate (Saint Helena Registry)", "Saint Helena Coroner clearance", "SA Airlink or RAF cargo documentation", "UK Coroner import notification"],
        "religion_notes": "Predominantly Christian (Anglican, Baptist, Catholic). Saint Helena has a small close-knit community.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility on Saint Helena, Ascension, or Tristan da Cunha.",
        "no_go_zones": "None.",
        "risk_highlights": "Extreme remoteness. Very limited medical facilities. Flight frequency from Saint Helena Airport is severely restricted. Tristan da Cunha has no air connection."
    },
    "american-samoa": {
        "country_key": "american-samoa",
        "country_name": "American Samoa",
        "country_adjective": "American Samoan",
        "flag": "🇦🇸",
        "region": "Pacific",
        "languages": ["English", "Samoan"],
        "currency": "US dollar (USD)",
        "british_representation": "British High Commission, Wellington, New Zealand (non-resident); Honorary British Consul, Apia, Samoa",
        "embassy_type": "Non-resident High Commission",
        "embassy_city": "Wellington",
        "local_authority_involved": "American Samoa Department of Public Safety; Territory Medical Examiner; US federal and American Samoa territorial law applies",
        "main_airports": ["Pago Pago International Airport (PPG)"],
        "routing_notes": "No direct UK flights. Routing via Honolulu (HNL) on Hawaiian Airlines then onward to UK from US gateway, or via Auckland (AKL) or Sydney (SYD). US transit documentation required.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 35,
        "timeline_notes": "US legal requirements and limited flight connections are the main timing factors. US federal embalming and documentation rules apply for international air transport.",
        "complexity_rating": "High",
        "complexity_notes": "US unincorporated territory — US federal law governs. Medical Examiner jurisdiction for non-natural deaths. Limited flight options and US transit documentation add complexity.",
        "required_documents": ["Death certificate (American Samoa Vital Statistics)", "Medical Examiner clearance (non-natural deaths)", "US federal embalming and air transport certificate", "US transit documentation", "UK Coroner import notification"],
        "religion_notes": "Predominantly Christian (Congregationalist, Catholic, Methodist). Fa'asamoa (Samoan traditional customs) may influence family preferences.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility in American Samoa.",
        "no_go_zones": "None.",
        "risk_highlights": "Tropical cyclones June–November. Tsunami risk (Pacific Ring of Fire). Limited medical facilities outside Lyndon B. Johnson Tropical Medical Center in Pago Pago."
    },
    "french-guiana": {
        "country_key": "french-guiana",
        "country_name": "French Guiana",
        "country_adjective": "French Guianese",
        "flag": "🇬🇫",
        "region": "South America",
        "languages": ["French"],
        "currency": "Euro (EUR)",
        "british_representation": "British Embassy, Paris, France (non-resident)",
        "embassy_type": "Non-resident Embassy",
        "embassy_city": "Paris",
        "local_authority_involved": "Mairie (civil registration); Gendarmerie nationale / Police nationale; French civil law — legally part of France",
        "main_airports": ["Cayenne-Felix Eboue Airport (CAY)"],
        "routing_notes": "Direct Air France flights CAY–Paris CDG approx 9h. All documentation in French — certified English translation required.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 7,
        "typical_timeline_days_max": 21,
        "timeline_notes": "French overseas department — same process as mainland France. Direct flight makes routing straightforward. Translation and French civil registration are primary timing factors.",
        "complexity_rating": "Moderate",
        "complexity_notes": "Legally part of France. French civil law. All documentation in French requires certified translation. Security situation varies in interior jungle regions — Gendarmerie clearance required for non-natural deaths.",
        "required_documents": ["Acte de deces (mairie) + certified English translation", "Gendarmerie/Police clearance (non-natural deaths)", "Certificat d'embaumement", "Certificat de non-contagion", "Autorisation de sortie du territoire", "UK Coroner import notification"],
        "religion_notes": "Predominantly Catholic with Evangelical Christian minority. Indigenous and Maroon communities in the interior may have traditional practices.",
        "cremation_available": True,
        "cremation_notes": "Cremation available in Cayenne.",
        "no_go_zones": "Interior jungle regions — limited infrastructure, significant journey times. Gold-mining areas near Suriname and Brazil borders have security risks.",
        "risk_highlights": "Malaria risk in interior jungle. Interior travel significantly lengthens repatriation. Gold-mining border areas have crime risk. Cayenne Kourou area (Ariane rocket launch site) has no special repatriation impact."
    }
}

for key, country in batch.items():
    data['countries'][key] = country
    print(f"ADDED: {key}")

with open('site/data/countries_repatriation.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Total countries: {len(data['countries'])}")
