import json

with open('site/data/countries_repatriation.json', encoding='utf-8') as f:
    data = json.load(f)

batch29 = {
    "sao-tome-and-principe": {
        "country_key": "sao-tome-and-principe",
        "country_name": "São Tomé and Príncipe",
        "country_adjective": "São Toméan",
        "flag": "\U0001f1f8\U0001f1f9",
        "region": "Central Africa",
        "languages": ["Portuguese"],
        "currency": "São Tomé and Príncipe dobra (STN)",
        "british_representation": "Non-resident. UK consular services provided by the British High Commission in Yaoundé, Cameroon.",
        "embassy_type": "non-resident",
        "embassy_city": "Yaoundé",
        "local_authority_involved": "Conservatória do Registo Civil, Ministério do Interior",
        "main_airports": ["São Tomé International Airport (TMS)"],
        "routing_notes": "Repatriations route via Lisbon (TAP Air Portugal operates São Tomé to Lisbon) or via Luanda (TAAG Angola Airlines). The Lisbon connection is the standard repatriation route to the UK.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 42,
        "timeline_notes": "Portuguese civil law documentation through the Conservatória do Registo Civil. Export permit issued by the Ministério do Interior. Non-resident British High Commission Yaoundé adds coordination time. Island geography means all transport is via São Tomé International Airport.",
        "complexity_rating": "high",
        "complexity_notes": "Portuguese-language documentation, non-resident UK diplomatic presence, and island geography with limited direct flights create a challenging repatriation environment. Príncipe island has additional logistical layers — internal transfer to São Tomé is required before international repatriation can begin. Cold storage and mortuary capacity on the islands is limited.",
        "required_documents": ["Death certificate (certidão de óbito)", "Embalming certificate", "Freedom from infection certificate", "Export permit (Ministério do Interior)", "UK Coroner permission if required", "Consular death registration with British High Commission Yaoundé"],
        "religion_notes": "Predominantly Catholic (c.85%), with Protestant and indigenous traditions. No significant Islamic burial timeline pressure.",
        "cremation_available": False,
        "cremation_notes": "Cremation facilities are not available in São Tomé and Príncipe. Remains must be repatriated to the UK for cremation.",
        "no_go_zones": [],
        "risk_highlights": ["Island geography — all repatriation exits via São Tomé International Airport", "Deaths on Príncipe island require internal transfer first", "Limited mortuary and cold storage capacity", "Non-resident UK coverage from Yaoundé adds coordination time"]
    },
    "equatorial-guinea": {
        "country_key": "equatorial-guinea",
        "country_name": "Equatorial Guinea",
        "country_adjective": "Equatoguinean",
        "flag": "\U0001f1ec\U0001f1f6",
        "region": "Central Africa",
        "languages": ["Spanish", "French", "Portuguese"],
        "currency": "Central African CFA franc (XAF)",
        "british_representation": "Non-resident. UK consular services provided by the British High Commission in Yaoundé, Cameroon.",
        "embassy_type": "non-resident",
        "embassy_city": "Yaoundé",
        "local_authority_involved": "Registro Civil, Ministerio del Interior y Corporaciones Locales",
        "main_airports": ["Malabo Airport (SSG), Bioko Island", "Mongomo Airport (GEM), mainland"],
        "routing_notes": "Malabo (Bioko Island) is the main international gateway. Air France operates Malabo to Paris CDG. Ethiopian Airlines serves Malabo via Addis Ababa. The mainland Río Muni region uses Malabo as the hub airport after internal transfer.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 42,
        "timeline_notes": "Spanish civil law documentation through the Registro Civil. Export authorisation from the Ministerio del Interior. Non-resident British High Commission Yaoundé adds coordination time. Deaths on the mainland (Río Muni) require transfer to Malabo before international repatriation.",
        "complexity_rating": "high",
        "complexity_notes": "Equatorial Guinea has the only Spanish-speaking government in sub-Saharan Africa. The country is split between Bioko Island (Malabo) and the mainland Río Muni enclave. Authoritarian governance under President Teodoro Obiang Nguema since 1979 means bureaucratic processes can be unpredictable. Non-resident UK coverage from Yaoundé adds coordination complexity. Freedom of movement for foreign nationals is restricted in some areas.",
        "required_documents": ["Certificado de defunción (death certificate)", "Embalming certificate", "Freedom from infection certificate", "Export permit (Ministerio del Interior)", "UK Coroner permission if required", "Consular death registration with British High Commission Yaoundé"],
        "religion_notes": "Predominantly Catholic (c.88%), with a small Protestant minority. No significant Islamic burial timeline pressure.",
        "cremation_available": False,
        "cremation_notes": "Cremation facilities are not available in Equatorial Guinea. Remains must be repatriated to the UK for cremation.",
        "no_go_zones": ["Border areas between Río Muni and Cameroon/Gabon"],
        "risk_highlights": ["Authoritarian governance — bureaucratic unpredictability", "Country split between island (Bioko) and mainland (Río Muni) — internal transfer required for mainland deaths", "Non-resident UK coverage from Yaoundé adds coordination time", "Restrictions on freedom of movement for foreign nationals"]
    },
    "haiti": {
        "country_key": "haiti",
        "country_name": "Haiti",
        "country_adjective": "Haitian",
        "flag": "\U0001f1ed\U0001f1f9",
        "region": "Caribbean",
        "languages": ["French", "Haitian Creole"],
        "currency": "Haitian gourde (HTG)",
        "british_representation": "Non-resident. UK consular services provided by the British High Commission in Kingston, Jamaica.",
        "embassy_type": "non-resident",
        "embassy_city": "Kingston",
        "local_authority_involved": "Office National d'Identification (ONI), Parquet Civil",
        "main_airports": ["Toussaint Louverture International Airport (PAP), Port-au-Prince"],
        "routing_notes": "Repatriations route via Miami (American Airlines), New York (JFK), or via other Caribbean hubs. Air France previously operated direct Paris service; connectivity is limited and subject to security-driven schedule changes.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 28,
        "typical_timeline_days_max": 90,
        "timeline_notes": "Repatriation from Haiti is severely complicated by gang violence, a dysfunctional state apparatus, and ongoing political instability. Civil registration has collapsed in large parts of Port-au-Prince. Timelines are highly unpredictable and heavily dependent on security conditions at the time of death.",
        "complexity_rating": "very-high",
        "complexity_notes": "FCDO advises against all but essential travel to Haiti. Gang violence controls large parts of Port-au-Prince and other cities. The Multinational Security Support Mission (MSS), led by Kenya, began deploying in 2024 but the security situation remains severe. Civil registration infrastructure has collapsed in gang-controlled areas. The Office National d'Identification (ONI) processes death documentation but access to offices in insecure areas is not guaranteed. Cold storage and mortuary capacity is extremely limited outside the capital.",
        "required_documents": ["Acte de décès (death certificate)", "Parquet Civil clearance", "Embalming certificate", "Freedom from infection certificate", "Export permit", "UK Coroner permission if required", "Consular death registration with British High Commission Kingston"],
        "religion_notes": "Mix of Catholicism, Protestantism, and Vodou traditions. Vodou funerary practices vary widely and may affect timing and handling of remains.",
        "cremation_available": False,
        "cremation_notes": "Cremation facilities are not available in Haiti. Remains must be repatriated to the UK for cremation.",
        "no_go_zones": ["Most of Port-au-Prince (gang-controlled areas)", "Artibonite department", "Cité Soleil and surrounding metropolitan zone", "Anywhere outside Pétionville and secured international compound areas"],
        "risk_highlights": ["FCDO advises against all but essential travel", "Gang violence controls large parts of Port-au-Prince and Artibonite", "Civil registration has collapsed in gang-controlled areas", "MSS (Kenyan-led multinational force) deploying since 2024 — security situation remains severe", "Extremely limited mortuary capacity", "Non-resident UK coverage from Kingston adds coordination time"]
    },
    "nicaragua": {
        "country_key": "nicaragua",
        "country_name": "Nicaragua",
        "country_adjective": "Nicaraguan",
        "flag": "\U0001f1f3\U0001f1ee",
        "region": "Central America",
        "languages": ["Spanish"],
        "currency": "Nicaraguan córdoba (NIO)",
        "british_representation": "Non-resident. UK consular services provided by the British Embassy in San José, Costa Rica.",
        "embassy_type": "non-resident",
        "embassy_city": "San José",
        "local_authority_involved": "Registro del Estado Civil de las Personas (RECP), Ministerio del Interior",
        "main_airports": ["Augusto C. Sandino International Airport (MGA), Managua"],
        "routing_notes": "Repatriations route via Miami (American Airlines), Houston (United Airlines), or via other Central American hubs such as San José, Costa Rica (Copa Airlines via Panama). Miami connections to the UK are straightforward.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 35,
        "timeline_notes": "Spanish civil law documentation through the Registro del Estado Civil de las Personas. Export permit from the Ministerio del Interior. Non-resident British Embassy San José coordinates consular registration. Documentation processes in Managua are generally predictable.",
        "complexity_rating": "high",
        "complexity_notes": "Nicaragua's authoritarian government under President Daniel Ortega maintains strict controls on civil society and movement of foreign nationals. FCDO advises against non-essential travel. Political tensions following the 2018 crackdown on protests remain elevated. Bureaucratic processes involving foreign nationals can be unpredictable. Non-resident UK embassy coverage from San José adds coordination time.",
        "required_documents": ["Certificado de defunción (death certificate)", "Embalming certificate", "Freedom from infection certificate", "Export permit (Ministerio del Interior)", "UK Coroner permission if required", "Consular death registration with British Embassy San José"],
        "religion_notes": "Predominantly Catholic (c.58%), with a large Evangelical Protestant minority (c.33%). No significant Islamic burial timeline pressure.",
        "cremation_available": False,
        "cremation_notes": "Cremation facilities are limited in Nicaragua. Repatriation of the body to the UK is the standard approach for UK nationals.",
        "no_go_zones": ["Caribbean Coast Autonomous Regions (remote jungle areas)", "Border areas with Honduras (Río Coco region)"],
        "risk_highlights": ["FCDO advises against all but essential travel", "Authoritarian governance — bureaucratic unpredictability for foreign nationals", "Non-resident UK coverage from San José adds coordination time", "Remote Caribbean coast has limited logistics infrastructure"]
    },
    "paraguay": {
        "country_key": "paraguay",
        "country_name": "Paraguay",
        "country_adjective": "Paraguayan",
        "flag": "\U0001f1f5\U0001f1fe",
        "region": "South America",
        "languages": ["Spanish", "Guaraní"],
        "currency": "Paraguayan guaraní (PYG)",
        "british_representation": "Non-resident. UK consular services provided by the British Embassy in Buenos Aires, Argentina.",
        "embassy_type": "non-resident",
        "embassy_city": "Buenos Aires",
        "local_authority_involved": "Dirección General del Registro Civil del Estado Civil de las Personas, Ministerio del Interior",
        "main_airports": ["Silvio Pettirossi International Airport (ASU), Asunción"],
        "routing_notes": "Repatriations route via Buenos Aires (Aerolíneas Argentinas or LATAM), São Paulo (LATAM/GOL), or via Miami. Buenos Aires Ezeiza is the most common connection point for UK routing.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 35,
        "timeline_notes": "Spanish civil law documentation through the Dirección General del Registro Civil. Export permit from the Ministerio del Interior. Non-resident British Embassy Buenos Aires handles consular registration. Documentation in Asunción is generally efficient.",
        "complexity_rating": "moderate",
        "complexity_notes": "Paraguay has a functioning civil registration system and an established international airport at Asunción. The main complexity factors are non-resident UK diplomatic coverage from Buenos Aires, the Spanish/Guaraní language context, and the remote Chaco region in the west where infrastructure is sparse. No active conflict zones. The Tri-Border Area (Paraguay, Argentina, Brazil) around Ciudad del Este has elevated organised crime activity.",
        "required_documents": ["Certificado de defunción (death certificate)", "Embalming certificate", "Freedom from infection certificate", "Export permit (Ministerio del Interior)", "UK Coroner permission if required", "Consular death registration with British Embassy Buenos Aires"],
        "religion_notes": "Predominantly Catholic (c.89%). No significant Islamic burial timeline pressure.",
        "cremation_available": True,
        "cremation_notes": "Cremation services are available in Asunción. If UK cremation is preferred, full repatriation is required. Ashes can also be repatriated; see the bringing ashes home guidance for Paraguay.",
        "no_go_zones": ["Remote Chaco region (extreme west)", "Tri-Border Area around Ciudad del Este (elevated organised crime)"],
        "risk_highlights": ["Non-resident UK coverage from Buenos Aires adds coordination time", "Remote Chaco region has very limited infrastructure", "Tri-Border Area (Ciudad del Este) has elevated organised crime"]
    }
}

for key, country in batch29.items():
    data['countries'][key] = country
    print(f"ADDED: {key}")

with open('site/data/countries_repatriation.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Total countries: {len(data['countries'])}")
