import json, os

path = os.path.join(os.path.dirname(__file__), '..', 'site', 'data', 'countries_repatriation.json')
with open(path, encoding='utf-8') as f:
    data = json.load(f)

countries = {
    "pitcairn-islands": {
        "country_key": "pitcairn-islands",
        "country_name": "Pitcairn Islands",
        "country_adjective": "Pitcairn",
        "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "region": "South Pacific",
        "languages": ["English"],
        "currency": "New Zealand Dollar (NZD)",
        "british_representation": "Governor of the Pitcairn Islands (based in Auckland, New Zealand)",
        "embassy_type": "Governor's Office",
        "embassy_city": "Auckland",
        "local_authority_involved": "Island Magistrate's Court; Governor of Pitcairn Islands",
        "main_airports": ["None — no airport on Pitcairn. Supply vessel MV Claymore II from Mangareva (French Polynesia) every 3 months approximately. Mangareva reachable via Air Tahiti from Papeete (PPT)."],
        "routing_notes": "No airport exists on Pitcairn Island. Repatriation requires sea passage on the supply vessel from Pitcairn to Mangareva (French Polynesia), then Air Tahiti Mangareva–Papeete (PPT), then Air France PPT–CDG (~22h), then UK. Henderson, Ducie and Oeno Islands are uninhabited. Population approximately 45 residents. Vessel schedule is approximately quarterly; bespoke charter arrangements may be necessary.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 30,
        "typical_timeline_days_max": 90,
        "timeline_notes": "Highly variable. Dependent on supply vessel schedule (approximately quarterly). Bespoke charter may shorten timeline significantly but at exceptional cost.",
        "complexity_rating": "Very High",
        "complexity_notes": "Pitcairn is the world's most isolated permanently inhabited British territory. No airport, minimal infrastructure, quarterly supply vessels, and a population of approximately 45 residents create exceptional logistical difficulty. The Governor is based in Auckland. UK FCO involvement essential from the outset.",
        "required_documents": ["Pitcairn Islands death certificate (issued by the Island Registrar)", "UK consular death registration via Governor's Office", "Embalming certificate (if applicable)", "Repatriation authority from Governor's Office", "Funeral director documentation", "UK receiving funeral director confirmation", "Cargo documentation for each transport leg"],
        "religion_notes": "Majority Seventh-day Adventist. Burial preferences should be discussed with the family and Island Pastor.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility. Burial on Pitcairn or repatriation are the only options.",
        "no_go_zones": "Henderson Island (UNESCO World Heritage Site, uninhabited), Ducie and Oeno atolls (uninhabited). No specific on-island no-go zones for Pitcairn village.",
        "risk_highlights": ["Extreme isolation — supply vessel schedule governs all logistics", "No airport — sea passage mandatory", "Very small population means limited local funeral support", "Governor based in Auckland — remote administration", "French Polynesia transit documentation required (CITES not applicable but standard transit paperwork)"]
    },
    "cocos-keeling-islands": {
        "country_key": "cocos-keeling-islands",
        "country_name": "Cocos (Keeling) Islands",
        "country_adjective": "Cocos Islander",
        "flag": "🇨🇨",
        "region": "Indian Ocean",
        "languages": ["English", "Cocos Malay"],
        "currency": "Australian Dollar (AUD)",
        "british_representation": "British High Commission Canberra, Australia (non-resident); Honorary Consul Perth",
        "embassy_type": "High Commission (non-resident)",
        "embassy_city": "Canberra",
        "local_authority_involved": "Administrator of Cocos (Keeling) Islands; Australian Federal Police; Western Australia Coroner (for coronial matters)",
        "main_airports": ["Cocos (Keeling) Islands Airport (CCK) — Cocos Keeling to Perth (PER) via Virgin Australia, approximately 3h"],
        "routing_notes": "Australian external territory administered under Australian law. Death registration and repatriation follow Australian (Western Australia) legal framework. Flights from CCK to Perth (PER) operate approximately twice weekly via Virgin Australia. Perth to UK: Qantas or partner airlines PER–LHR ~17h. UK consular assistance via BHC Canberra.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 10,
        "typical_timeline_days_max": 28,
        "timeline_notes": "Limited flight frequency from CCK to Perth can extend timeline. Once in Perth, standard international repatriation timelines apply.",
        "complexity_rating": "High",
        "complexity_notes": "Remote Australian external territory. Limited flight frequency, Australian law applies, and UK consular assistance operates through BHC Canberra. Two distinct island groups: Direction Island/West Island (airstrip) and Home Island (Cocos Malay community). Deaths on Home Island require transfer to West Island for repatriation.",
        "required_documents": ["Australian death certificate (via Administrator's Office)", "Western Australia Coroner's release (non-natural deaths)", "Australian embalming certificate", "Airworthiness documentation for air transport", "UK receiving funeral director confirmation", "Australian export permit for human remains", "BHC Canberra notification"],
        "religion_notes": "Home Island population is predominantly Muslim (Cocos Malay community). Islamic burial timing requirements may create urgency. West Island population is largely non-religious or Christian.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility on the islands. Remains must be transferred to Perth or Australian mainland for cremation.",
        "no_go_zones": "No formal no-go zones. North Keeling Island is a national park (Pulu Keeling) — uninhabited, restricted access.",
        "risk_highlights": ["Limited flight frequency from CCK to Perth", "Islamic community on Home Island — burial timing sensitivity", "Australian law applies — UK families may be unfamiliar with process", "Remote location — limited local funeral service infrastructure"]
    },
    "christmas-island": {
        "country_key": "christmas-island",
        "country_name": "Christmas Island",
        "country_adjective": "Christmas Islander",
        "flag": "🇨🇽",
        "region": "Indian Ocean",
        "languages": ["English", "Malay", "Chinese (various)"],
        "currency": "Australian Dollar (AUD)",
        "british_representation": "British High Commission Canberra, Australia (non-resident); Honorary Consul Perth",
        "embassy_type": "High Commission (non-resident)",
        "embassy_city": "Canberra",
        "local_authority_involved": "Administrator of Christmas Island; Australian Federal Police; Western Australia Coroner",
        "main_airports": ["Christmas Island Airport (XCH) — Christmas Island to Perth (PER) via Virgin Australia, approximately 3.5h"],
        "routing_notes": "Australian external territory in the Indian Ocean. Australian law applies. Flights from XCH to Perth (PER) operate approximately twice weekly via Virgin Australia. Perth to UK: Qantas or partner airlines PER–LHR ~17h. UK consular assistance via BHC Canberra.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 10,
        "typical_timeline_days_max": 28,
        "timeline_notes": "Limited flight frequency from XCH to Perth can extend timeline. Once in Perth, standard international repatriation timelines apply.",
        "complexity_rating": "High",
        "complexity_notes": "Remote Australian external territory. Population approximately 2000, predominantly Chinese and Malay. Limited flight frequency and Australian legal framework. Asylum seeker processing centre on island adds administrative complexity. UK consular support operates remotely through BHC Canberra.",
        "required_documents": ["Australian death certificate (via Administrator's Office)", "Western Australia Coroner's release (non-natural deaths)", "Australian embalming certificate", "Airworthiness documentation for air transport", "UK receiving funeral director confirmation", "Australian export permit for human remains", "BHC Canberra notification"],
        "religion_notes": "Significant Muslim (Malay) and Buddhist (Chinese) communities. Burial timing expectations may vary. Confirm religious observance needs with the family.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility on the island. Remains must be transferred to Perth for cremation.",
        "no_go_zones": "Immigration detention facility areas are restricted. The Flying Fish Cove and Settlement areas are the main population centres.",
        "risk_highlights": ["Limited flight frequency from XCH to Perth", "Diverse community — religious and cultural burial expectations vary", "Asylum processing administration adds bureaucratic complexity", "Australian law applies — UK families may be unfamiliar with process"]
    },
    "norfolk-island": {
        "country_key": "norfolk-island",
        "country_name": "Norfolk Island",
        "country_adjective": "Norfolk Islander",
        "flag": "🇳🇫",
        "region": "South Pacific",
        "languages": ["English", "Norfuk (local creole)"],
        "currency": "Australian Dollar (AUD)",
        "british_representation": "British High Commission Canberra, Australia (non-resident)",
        "embassy_type": "High Commission (non-resident)",
        "embassy_city": "Canberra",
        "local_authority_involved": "Administrator of Norfolk Island; Australian Federal Police; New South Wales Coroner (for coronial matters post-2016)",
        "main_airports": ["Norfolk Island Airport (NLK) — direct flights to Sydney (SYD) ~2h and Brisbane (BNE) ~2.5h via Qantas/Air New Zealand"],
        "routing_notes": "Australian external territory since 2016 when self-government was abolished. Australian federal law applies. Direct flights from NLK to Sydney (SYD) or Brisbane (BNE) approximately 3x weekly. UK connections via SYD–LHR or BNE–LHR Qantas ~21h. UK consular assistance via BHC Canberra.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 7,
        "typical_timeline_days_max": 21,
        "timeline_notes": "Moderate complexity. Direct flights to Australia available approximately 3x weekly. Once in Sydney or Brisbane, onward connections to UK are straightforward.",
        "complexity_rating": "Moderate",
        "complexity_notes": "Norfolk Island's governance changed in 2016 — Australian federal law now applies, replacing the previous self-governing framework. Families should be aware that the Coroner's jurisdiction now falls under New South Wales. Population approximately 1800. UK consular support via BHC Canberra.",
        "required_documents": ["Australian death certificate (via Administrator's Office, Norfolk Island)", "New South Wales Coroner's release (non-natural deaths)", "Australian embalming certificate", "Airworthiness documentation for air transport", "UK receiving funeral director confirmation", "Australian export permit for human remains"],
        "religion_notes": "Predominantly Christian. Anglican and Seventh-day Adventist communities present, reflecting the island's Bounty Mutiny heritage.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility on Norfolk Island. Remains must be transferred to Sydney or Brisbane for cremation.",
        "no_go_zones": "Kingston Archaeological Area (UNESCO World Heritage Site tentative list) has restricted access in some heritage zones.",
        "risk_highlights": ["Flight frequency to Australia is limited (~3x weekly)", "2016 governance change — Australian federal law applies, not self-governing rules", "Remote South Pacific location — limited local funeral service infrastructure", "UK consular assistance is remote via BHC Canberra"]
    },
    "tokelau": {
        "country_key": "tokelau",
        "country_name": "Tokelau",
        "country_adjective": "Tokelauan",
        "flag": "🇹🇰",
        "region": "South Pacific",
        "languages": ["Tokelauan", "English"],
        "currency": "New Zealand Dollar (NZD)",
        "british_representation": "British High Commission Wellington, New Zealand (non-resident)",
        "embassy_type": "High Commission (non-resident)",
        "embassy_city": "Wellington",
        "local_authority_involved": "Tokelau National Government (Taupulega); New Zealand Ministry of Foreign Affairs and Trade; New Zealand Coroner (in practice)",
        "main_airports": ["No airport on any of the three atolls. Vessel from Apia, Samoa (APW) — approximately 2-day sea voyage. Apia served by Samoa Airways/Air New Zealand."],
        "routing_notes": "Tokelau has no airport. The only access is by vessel from Apia, Samoa, taking approximately 2 days. All three atolls (Atafu, Nukunonu, Fakaofo) are accessible only by sea. Repatriation requires vessel transfer to Apia, then flights Apia (APW) to Auckland (AKL) ~3h, then Auckland–LHR Qantas/Air New Zealand ~26h. Vessel frequency is approximately fortnightly. New Zealand law and consular support applies throughout.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 45,
        "timeline_notes": "Highly dependent on vessel schedule (approximately fortnightly). Sea voyage to Samoa adds 2 days minimum. Once in Auckland, standard international timelines apply.",
        "complexity_rating": "Very High",
        "complexity_notes": "Tokelau is a non-self-governing territory of New Zealand with no airport on any of its three atolls. All repatriation logistics depend on fortnightly vessel schedules. New Zealand law applies and the NZ Ministry of Foreign Affairs and Trade administers the territory. UK consular assistance via BHC Wellington. The combined sea-and-air journey to the UK requires careful coordination across multiple carriers and authorities.",
        "required_documents": ["New Zealand death certificate (via Tokelau National Government and MFAT)", "New Zealand Coroner's release (non-natural deaths)", "Embalming certificate (if applicable)", "Vessel cargo documentation", "Samoa transit documentation", "Airworthiness documentation for air transport from Samoa/Auckland", "UK receiving funeral director confirmation", "NZ export permit for human remains"],
        "religion_notes": "Predominantly Congregationalist Christian (Atafu and Fakaofo) and Roman Catholic (Nukunonu). Burial customs observed; discuss with family and local village elders.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility. Burial on atoll or repatriation are the only options.",
        "no_go_zones": "No formal no-go zones. All three atolls are low-lying — maximum elevation approximately 5 metres — creating acute climate vulnerability. No militarised or restricted zones.",
        "risk_highlights": ["No airport — vessel schedule governs all logistics (fortnightly)", "2-day sea voyage to Samoa before air repatriation can begin", "Three atolls — death on a different atoll to the vessel stop adds further delay", "New Zealand law applies — coordination via MFAT Wellington", "Extreme remoteness with minimal local funeral infrastructure"]
    }
}

for key, country in countries.items():
    data['countries'][key] = country
    print(f"ADDED: {key}")

with open(path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Total countries: {len(data['countries'])}")
