import json

with open('site/data/countries_repatriation.json', encoding='utf-8') as f:
    data = json.load(f)

batch = {
    "puerto-rico": {
        "country_key": "puerto-rico",
        "country_name": "Puerto Rico",
        "country_adjective": "Puerto Rican",
        "flag": "🇵🇷",
        "region": "Caribbean",
        "languages": ["Spanish", "English"],
        "currency": "US dollar (USD)",
        "british_representation": "British Embassy, Washington DC (non-resident); Honorary British Consul, San Juan",
        "embassy_type": "Non-resident Embassy",
        "embassy_city": "San Juan",
        "local_authority_involved": "Puerto Rico Institute of Forensic Sciences (non-natural deaths); Puerto Rico Vital Statistics Registry; US federal and Puerto Rico territorial law applies",
        "main_airports": ["Luis Munoz Marin International Airport (SJU)"],
        "routing_notes": "Direct British Airways SJU–LHR approx 8.5h. Also American Airlines SJU–ORD/MIA/JFK then UK connections. US federal embalming and documentation rules apply for international air transport.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 7,
        "typical_timeline_days_max": 21,
        "timeline_notes": "US federal law governs body export from Puerto Rico — forensic clearance and US documentation requirements are the main timing factors. Direct BA flight to Heathrow is practical.",
        "complexity_rating": "Moderate",
        "complexity_notes": "US unincorporated territory — US federal law and Puerto Rico territorial law apply. Institute of Forensic Sciences jurisdiction for non-natural deaths. US federal embalming certificate required. Direct UK flight available.",
        "required_documents": ["Death certificate (Puerto Rico Vital Statistics Registry)", "Institute of Forensic Sciences clearance (non-natural deaths)", "US federal embalming and air transport certificate", "UK Coroner import notification"],
        "religion_notes": "Predominantly Catholic with significant evangelical Protestant community. Full range of faith funeral services available in San Juan.",
        "cremation_available": True,
        "cremation_notes": "Cremation available in Puerto Rico.",
        "no_go_zones": "None.",
        "risk_highlights": "Hurricane season June–November. Occasional earthquake activity. Infrastructure in some rural inland areas may be affected by storm damage. Medical facilities in San Juan are good; rural areas have limited resources."
    },
    "guam": {
        "country_key": "guam",
        "country_name": "Guam",
        "country_adjective": "Guamanian",
        "flag": "🇬🇺",
        "region": "Pacific",
        "languages": ["English", "Chamorro"],
        "currency": "US dollar (USD)",
        "british_representation": "British Embassy, Tokyo, Japan (non-resident)",
        "embassy_type": "Non-resident Embassy",
        "embassy_city": "Tokyo",
        "local_authority_involved": "Guam Medical Examiner; Guam Vital Statistics; US federal and Guam territorial law applies",
        "main_airports": ["Antonio B. Won Pat International Airport (GUM)"],
        "routing_notes": "No direct UK flights. Routing via Tokyo Narita (NRT) or Tokyo Haneda (HND) on United Airlines or Japan Airlines, then UK connections from Tokyo. Also via Honolulu (HNL). Very long-haul transit — allow 24+ hours routing time.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 14,
        "typical_timeline_days_max": 35,
        "timeline_notes": "Remote Pacific location with no direct UK routing. US federal law requirements, Medical Examiner clearance, and multi-leg routing via Tokyo or Honolulu are the main timing factors.",
        "complexity_rating": "High",
        "complexity_notes": "US organised territory, western Pacific. US federal law governs body export. Medical Examiner jurisdiction for non-natural deaths. No direct UK routing — multi-leg via Tokyo or Honolulu. British Embassy Tokyo covers on non-resident basis.",
        "required_documents": ["Death certificate (Guam Vital Statistics)", "Medical Examiner clearance (non-natural deaths)", "US federal embalming and air transport certificate", "UK Coroner import notification"],
        "religion_notes": "Predominantly Catholic (Chamorro traditional faith). Also Protestant and non-denominational Christian communities.",
        "cremation_available": True,
        "cremation_notes": "Cremation available in Guam.",
        "no_go_zones": "None.",
        "risk_highlights": "Typhoon risk June–November. North Korea ballistic missile overflight risk (historically — check FCDO current advice). US military presence throughout the island. Medical facilities are reasonable for the Pacific."
    },
    "us-virgin-islands": {
        "country_key": "us-virgin-islands",
        "country_name": "US Virgin Islands",
        "country_adjective": "Virgin Islander",
        "flag": "🇻🇮",
        "region": "Caribbean",
        "languages": ["English"],
        "currency": "US dollar (USD)",
        "british_representation": "British Embassy, Washington DC (non-resident); Honorary British Consul, Barbados covers Eastern Caribbean",
        "embassy_type": "Non-resident Embassy",
        "embassy_city": "Washington DC",
        "local_authority_involved": "US Virgin Islands Medical Examiner; USVI Vital Statistics Bureau; US federal and USVI territorial law applies",
        "main_airports": ["Cyril E. King Airport, St Thomas (STT)", "Henry E. Rohlsen Airport, St Croix (STX)"],
        "routing_notes": "No direct UK flights. Routing via Miami (MIA) or San Juan Puerto Rico (SJU) then UK connections. American Airlines and United operate the main connections. US federal documentation requirements apply.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 7,
        "typical_timeline_days_max": 21,
        "timeline_notes": "Caribbean US territory — relatively close routing via Miami or San Juan. US federal law governs export. Medical Examiner clearance for non-natural deaths is the primary timing factor.",
        "complexity_rating": "Moderate",
        "complexity_notes": "US organised territory. US federal law and USVI territorial law apply. Medical Examiner jurisdiction. Routing via Miami or Puerto Rico is well-established. St John and Water Island deaths require inter-island transfer to St Thomas or St Croix.",
        "required_documents": ["Death certificate (USVI Vital Statistics Bureau)", "Medical Examiner clearance (non-natural deaths)", "US federal embalming and air transport certificate", "UK Coroner import notification"],
        "religion_notes": "Predominantly Christian (Protestant, Catholic). Full range of services available on St Thomas and St Croix.",
        "cremation_available": True,
        "cremation_notes": "Cremation available on St Thomas and St Croix.",
        "no_go_zones": "None.",
        "risk_highlights": "Hurricane season June–November. Crime in some areas of St Croix and St Thomas — check FCDO travel advice. Deaths on St John require transfer to St Thomas. Water Island: ferry transfer to St Thomas."
    },
    "greenland": {
        "country_key": "greenland",
        "country_name": "Greenland",
        "country_adjective": "Greenlandic",
        "flag": "🇬🇱",
        "region": "Arctic / North Atlantic",
        "languages": ["Greenlandic (Kalaallisut)", "Danish"],
        "currency": "Danish krone (DKK)",
        "british_representation": "British Embassy, Copenhagen, Denmark (non-resident)",
        "embassy_type": "Non-resident Embassy",
        "embassy_city": "Copenhagen",
        "local_authority_involved": "Police of Greenland (Politiet i Gronland); civil registration through Danish system; Danish law applies",
        "main_airports": ["Nuuk Airport (GOH)", "Kangerlussuaq Airport (SFJ)", "Ilulissat Airport (JAV)"],
        "routing_notes": "Routing via Copenhagen (CPH) on Air Greenland or SAS. Kangerlussuaq is the main transit hub; Nuuk connections improving with new airport construction. Very limited frequency — Air Greenland schedule is the controlling factor.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 10,
        "typical_timeline_days_max": 28,
        "timeline_notes": "Limited Air Greenland flight frequency to Copenhagen is the primary scheduling constraint. Deaths outside Nuuk or Kangerlussuaq require inter-settlement transport which can take additional days.",
        "complexity_rating": "High",
        "complexity_notes": "Autonomous territory of Denmark — Danish law applies. Very remote. Limited flight frequency from most settlements. Deaths outside main centres may require helicopter or small aircraft transfer. All documentation in Greenlandic/Danish — certified English translation required.",
        "required_documents": ["Death certificate (Danish civil registration system) + certified English translation", "Police of Greenland clearance (non-natural deaths)", "Air Greenland or charter cargo documentation", "UK Coroner import notification"],
        "religion_notes": "Predominantly Evangelical Lutheran (Church of Greenland). Inuit traditional culture may influence family preferences in smaller communities.",
        "cremation_available": False,
        "cremation_notes": "Cremation is not available in Greenland. Bodies are repatriated to Denmark or the UK for cremation.",
        "no_go_zones": "Arctic ice cap and remote inland icefield — limited emergency response. Travel outside settlements requires specialist preparation.",
        "risk_highlights": "Extreme Arctic conditions. Limited medical facilities outside Nuuk. Sea ice and weather can close airports and ports for days. Dog sledge routes and ice cap traverses carry serious risk. Very limited emergency response capacity in remote settlements."
    },
    "faroe-islands": {
        "country_key": "faroe-islands",
        "country_name": "Faroe Islands",
        "country_adjective": "Faroese",
        "flag": "🇫🇴",
        "region": "North Atlantic",
        "languages": ["Faroese", "Danish"],
        "currency": "Danish krone (DKK) / Faroese krone",
        "british_representation": "British Embassy, Copenhagen, Denmark (non-resident)",
        "embassy_type": "Non-resident Embassy",
        "embassy_city": "Copenhagen",
        "local_authority_involved": "Faroese Police (Politiet i Faeroyerne); civil registration through Faroese system; Danish law applies with significant Faroese autonomy",
        "main_airports": ["Vagar Airport (FAE)"],
        "routing_notes": "Atlantic Airways direct FAE–LGW (London Gatwick) approx 2.5h. Also Atlantic Airways FAE–CPH then Copenhagen–UK. Infrequent schedule — Atlantic Airways operates limited rotations.",
        "typical_cost_gbp_min": 0,
        "typical_cost_gbp_max": 0,
        "typical_cost_notes": "Contact specialist firm for current pricing",
        "typical_timeline_days_min": 5,
        "typical_timeline_days_max": 14,
        "timeline_notes": "Atlantic Airways direct flight to Gatwick is very practical when available. Limited frequency is the main constraint — flights operate a handful of times per week.",
        "complexity_rating": "Low",
        "complexity_notes": "Autonomous territory of Denmark. Danish law applies. English widely spoken. Direct London Gatwick flight available. Documentation in Faroese/Danish requires certified English translation but processes are straightforward.",
        "required_documents": ["Death certificate (Faroese civil registration) + certified English translation", "Faroese Police clearance (non-natural deaths)", "Atlantic Airways cargo documentation", "UK Coroner import notification"],
        "religion_notes": "Predominantly Evangelical Lutheran (Church of the Faroe Islands). Small Plymouth Brethren community.",
        "cremation_available": False,
        "cremation_notes": "No cremation facility in the Faroe Islands. Bodies are repatriated to Denmark or the UK for cremation.",
        "no_go_zones": "None.",
        "risk_highlights": "Severe North Atlantic weather can delay flights significantly. Coastal cliff walking — significant fall risk on popular hiking routes. Very limited medical facilities outside Torshavn."
    }
}

for key, country in batch.items():
    data['countries'][key] = country
    print(f"ADDED: {key}")

with open('site/data/countries_repatriation.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Total countries: {len(data['countries'])}")
