Set-Location "C:\Users\garet\Desktop\funeral-repatriation\site\content\blog"

$fixes = @{
    "air-ambulance-vs-repatriation-after-death.md" = "Air Ambulance vs Repatriation After Death"
    "airline-bereavement-fares-death-abroad.md" = "Airline Bereavement Fares After a Death Abroad"
    "body-identification-abroad-uncertain-identity.md" = "Body Identification Abroad: Uncertain Identity"
    "bringing-ashes-home-on-a-passenger-flight.md" = "Bringing Ashes Home on a Passenger Flight"
    "bringing-ashes-through-connecting-flights.md" = "Bringing Ashes Through Connecting Flights"
    "british-embassy-role-death-abroad.md" = "The British Embassy's Role When Someone Dies Abroad"
    "death-abroad-muslim-countries.md" = "Death Abroad in a Muslim Country: UK Family Guide"
    "death-abroad-no-travel-insurance.md" = "No Travel Insurance When Someone Dies Abroad"
    "death-on-cruise-ship-repatriation.md" = "Death on a Cruise Ship: Repatriation Explained"
    "deaths-in-british-overseas-territories-and-crown-dependencies.md" = "Deaths in British Overseas Territories: UK Guide"
    "documents-needed-to-repatriate-body-to-uk.md" = "Documents Needed to Repatriate a Body to the UK"
    "family-disagreement-repatriation-or-burial-abroad.md" = "Family Disagreement About Repatriation: What to Do"
    "first-24-hours-after-a-death-abroad-checklist.md" = "First 24 Hours After a Death Abroad: Checklist"
    "hire-car-rental-property-death-abroad.md" = "Hire Car and Rental Property After a Death Abroad"
    "how-embalming-works-international-repatriation.md" = "How Embalming Works for International Repatriation"
    "how-long-does-repatriation-take.md" = "How Long Does Repatriation Take? Country Timelines"
    "how-to-choose-a-repatriation-company.md" = "How to Choose a Repatriation Company"
    "how-to-get-foreign-death-certificate-translated.md" = "How to Get a Foreign Death Certificate Translated"
    "how-to-prepare-for-dying-abroad.md" = "How to Prepare for the Possibility of Dying Abroad"
    "how-to-register-foreign-death-in-uk.md" = "How to Register a Foreign Death in the UK"
    "how-to-support-family-after-death-abroad.md" = "How to Support a Family After a Death Abroad"
    "local-funeral-director-abroad-mistakes.md" = "Why the Local Funeral Director Abroad Is a Risk"
    "medication-medical-equipment-death-abroad.md" = "Medication and Medical Equipment After Death Abroad"
    "missing-person-abroad-presumption-of-death.md" = "When a Body Cannot Be Found: Presumption of Death"
    "post-mortem-delay-travel-insurance-claim.md" = "How a Post-Mortem Delay Affects Insurance Claims"
    "post-mortem-delays-and-what-families-can-control.md" = "Post-Mortem Delays: What Families Can Control"
    "probate-and-estate-process-when-someone-dies-abroad.md" = "Probate and Estate When Someone Dies Abroad"
    "religious-cultural-requirements-repatriation.md" = "Religious and Cultural Requirements: Repatriation"
    "repatriation-by-road-from-europe.md" = "Repatriation by Road from Europe: How It Works"
    "repatriation-company-vs-funeral-director.md" = "Repatriation Company vs Funeral Director"
    "repatriation-cost-guide.md" = "How Much Does Repatriation Cost?"
    "repatriation-expat-vs-tourist.md" = "UK Expat vs Tourist Repatriation: Key Differences"
    "repatriation-from-conflict-zone-crisis-area.md" = "Repatriation from a Conflict Zone: Family Guide"
    "repatriation-from-albania-guide.md" = "Repatriation from Albania to the UK: Family Guide"
    "repatriation-from-algeria-guide.md" = "Repatriation from Algeria to the UK"
    "repatriation-from-argentina-guide.md" = "Repatriation from Argentina to the UK"
    "repatriation-from-australia-guide.md" = "Repatriation from Australia to the UK: Guide"
    "repatriation-from-austria-guide.md" = "Repatriation from Austria to the UK"
    "repatriation-from-bahrain-guide.md" = "Repatriation from Bahrain to the UK"
    "repatriation-from-bangladesh-guide.md" = "Repatriation from Bangladesh to the UK"
    "repatriation-from-belgium-guide.md" = "Repatriation from Belgium to the UK"
    "repatriation-from-bolivia-guide.md" = "Repatriation from Bolivia to the UK: Family Guide"
    "repatriation-from-brazil-guide.md" = "Repatriation from Brazil to the UK"
    "repatriation-from-bulgaria-guide.md" = "Repatriation from Bulgaria to the UK"
    "repatriation-from-cambodia-guide.md" = "Repatriation from Cambodia to the UK"
    "repatriation-from-canada-guide.md" = "Repatriation from Canada to the UK"
    "repatriation-from-chile-guide.md" = "Repatriation from Chile to the UK: Family Guide"
    "repatriation-from-china-guide.md" = "Repatriation from China to the UK"
    "repatriation-from-colombia-guide.md" = "Repatriation from Colombia to the UK"
    "repatriation-from-costa-rica-guide.md" = "Repatriation from Costa Rica to the UK: Guide"
    "repatriation-from-croatia-guide.md" = "Repatriation from Croatia to the UK"
    "repatriation-from-cuba-guide.md" = "Repatriation from Cuba to the UK"
    "repatriation-from-cyprus-guide.md" = "Repatriation from Cyprus to the UK"
    "repatriation-from-czech-republic-guide.md" = "Repatriation from the Czech Republic to the UK"
    "repatriation-from-denmark-guide.md" = "Repatriation from Denmark to the UK"
    "repatriation-from-dominican-republic-guide.md" = "Repatriation from the Dominican Republic to the UK"
    "repatriation-from-ecuador-guide.md" = "Repatriation from Ecuador to the UK: Family Guide"
    "repatriation-from-egypt-guide.md" = "Repatriation from Egypt to the UK"
    "repatriation-from-ethiopia-guide.md" = "Repatriation from Ethiopia to the UK"
    "repatriation-from-finland-guide.md" = "Repatriation from Finland to the UK: Family Guide"
    "repatriation-from-georgia-guide.md" = "Repatriation from Georgia to the UK: Family Guide"
    "repatriation-from-germany-guide.md" = "Repatriation from Germany to the UK"
    "repatriation-from-ghana-guide.md" = "Repatriation from Ghana to the UK"
    "repatriation-from-greece-guide.md" = "Repatriation from Greece to the UK"
    "repatriation-from-hong-kong-guide.md" = "Repatriation from Hong Kong to the UK"
    "repatriation-from-hungary-guide.md" = "Repatriation from Hungary to the UK"
    "repatriation-from-iceland-guide.md" = "Repatriation from Iceland to the UK"
    "repatriation-from-india-guide.md" = "Repatriation from India to the UK"
    "repatriation-from-indonesia-guide.md" = "Repatriation from Indonesia to the UK"
    "repatriation-from-ireland-guide.md" = "Repatriation from Ireland to the UK"
    "repatriation-from-israel-guide.md" = "Repatriation from Israel to the UK"
    "repatriation-from-italy-guide.md" = "Repatriation from Italy to the UK"
    "repatriation-from-jamaica-guide.md" = "Repatriation from Jamaica to the UK"
    "repatriation-from-japan-guide.md" = "Repatriation from Japan to the UK"
    "repatriation-from-jordan-guide.md" = "Repatriation from Jordan to the UK"
    "repatriation-from-kazakhstan-guide.md" = "Repatriation from Kazakhstan to the UK: Guide"
    "repatriation-from-kenya-guide.md" = "Repatriation from Kenya to the UK"
    "repatriation-from-kuwait-guide.md" = "Repatriation from Kuwait to the UK: Family Guide"
    "repatriation-from-lebanon-guide.md" = "Repatriation from Lebanon to the UK: Family Guide"
    "repatriation-from-malaysia-guide.md" = "Repatriation from Malaysia to the UK"
    "repatriation-from-maldives-guide.md" = "Repatriation from the Maldives to the UK"
    "repatriation-from-mauritius-guide.md" = "Repatriation from Mauritius to the UK: Guide"
    "repatriation-from-mexico-guide.md" = "Repatriation from Mexico to the UK"
    "repatriation-from-montenegro-guide.md" = "Repatriation from Montenegro to the UK: Guide"
    "repatriation-from-morocco-guide.md" = "Repatriation from Morocco to the UK"
    "repatriation-from-myanmar-guide.md" = "Repatriation from Myanmar to the UK"
    "repatriation-from-nepal-guide.md" = "Repatriation from Nepal to the UK"
    "repatriation-from-netherlands-guide.md" = "Repatriation from the Netherlands to the UK"
    "repatriation-from-new-zealand-guide.md" = "Repatriation from New Zealand to the UK"
    "repatriation-from-nigeria-guide.md" = "Repatriation from Nigeria to the UK"
    "repatriation-from-norway-guide.md" = "Repatriation from Norway to the UK"
    "repatriation-from-oman-guide.md" = "Repatriation from Oman to the UK"
    "repatriation-from-pakistan-guide.md" = "Repatriation from Pakistan to the UK"
    "repatriation-from-peru-guide.md" = "Repatriation from Peru to the UK"
    "repatriation-from-philippines-guide.md" = "Repatriation from the Philippines to the UK"
    "repatriation-from-poland-guide.md" = "Repatriation from Poland to the UK"
    "repatriation-from-portugal-guide.md" = "Repatriation from Portugal to the UK"
    "repatriation-from-qatar-guide.md" = "Repatriation from Qatar to the UK"
    "repatriation-from-romania-guide.md" = "Repatriation from Romania to the UK"
    "repatriation-from-rwanda-guide.md" = "Repatriation from Rwanda to the UK"
    "repatriation-from-saudi-arabia-guide.md" = "Repatriation from Saudi Arabia to the UK"
    "repatriation-from-serbia-guide.md" = "Repatriation from Serbia to the UK"
    "repatriation-from-singapore-guide.md" = "Repatriation from Singapore to the UK"
    "repatriation-from-slovenia-guide.md" = "Repatriation from Slovenia to the UK: Guide"
    "repatriation-from-south-korea-guide.md" = "Repatriation from South Korea to the UK"
    "repatriation-from-spain-guide.md" = "Repatriation from Spain to the UK"
    "repatriation-from-sri-lanka-guide.md" = "Repatriation from Sri Lanka to the UK"
    "repatriation-from-sweden-guide.md" = "Repatriation from Sweden to the UK"
    "repatriation-from-switzerland-guide.md" = "Repatriation from Switzerland to the UK"
    "repatriation-from-taiwan-guide.md" = "Repatriation from Taiwan to the UK: Family Guide"
    "repatriation-from-tanzania-guide.md" = "Repatriation from Tanzania to the UK"
    "repatriation-from-thailand-guide.md" = "Repatriation from Thailand to the UK"
    "repatriation-from-tunisia-guide.md" = "Repatriation from Tunisia to the UK: Family Guide"
    "repatriation-from-turkey-guide.md" = "Repatriation from Turkey to the UK"
    "repatriation-from-uae-guide.md" = "Repatriation from the UAE to the UK"
    "repatriation-from-uganda-guide.md" = "Repatriation from Uganda to the UK"
    "repatriation-from-usa-guide.md" = "Repatriation from the USA to the UK"
    "repatriation-from-venezuela-guide.md" = "Repatriation from Venezuela to the UK"
    "repatriation-from-vietnam-guide.md" = "Repatriation from Vietnam to the UK"
}

$updated = 0
foreach ($file in $fixes.Keys) {
    $fullPath = Join-Path (Get-Location) $file
    if (Test-Path $fullPath) {
        $content = [System.IO.File]::ReadAllText($fullPath, [System.Text.Encoding]::UTF8)
        $newTitle = $fixes[$file]
        $newContent = [System.Text.RegularExpressions.Regex]::Replace($content, '(?m)^title:.*$', "title: `"$newTitle`"")
        if ($content -ne $newContent) {
            [System.IO.File]::WriteAllText($fullPath, $newContent, [System.Text.Encoding]::UTF8)
            $updated++
        }
    }
}
Write-Host "Files updated: $updated"
